use put_nonblocking when possible
commaai/openpilot pull request #1288
Opened 2020-03-28 11:59 UTC by eFiniLan

use put_nonblocking instead of params.put when possible.

2020-03-29 19:46 UTC, pd0wm requested changes

2020-03-29 19:46 UTC, pd0wm commented on selfdrive/camerad/snapshot/snapshot.py
> +    put_nonblocking("IsTakingSnapshot", "0")
You don't want the asynchronous version in this file since that could cause race conditions.

2020-03-29 19:46 UTC, pd0wm commented on selfdrive/car/car_helpers.py
> +  put_nonblocking("CarVin", vin)
We can't use the asynchronous version here, since boardd is waiting for the vin to be set and change the safety mode.

2020-03-29 19:46 UTC, pd0wm commented on selfdrive/controls/controlsd.py
> +  put_nonblocking("CarParams", cp_bytes)
Other services are waiting for carParams to start. Use synchronous version here.

2020-03-29 19:46 UTC, pd0wm commented on selfdrive/registration.py
> +  put_nonblocking("GitCommit", get_git_commit(default=""))
Don't use asynchronous version in this file. It could cause a race condition where loggerd starts without the params set

2020-03-29 19:46 UTC, pd0wm commented on selfdrive/updated.py
> +  put_nonblocking("LastUpdateTime", t.encode('utf8'))
Don't use asynchronous version here. There could be a race condition where the UpdateAvailableParam is set, but the release notes aren't there yet.

Updated is also no in a critical loop, so timeouts don't matter.

2020-03-29 19:51 UTC, pd0wm commented on selfdrive/camerad/snapshot/snapshot.py
> +    put_nonblocking("IsTakingSnapshot", "0")
I don't think we need the asynchronous version here since it's not in a timing critical loop.

2020-03-31 04:15 UTC, eFiniLan commented
@pd0wm thanks for the feedback :)
regarding to registration process, I have seen a few cases where their devices failed to authenticate due to modify persist partition (e.g. key deleted and regenerated).

The current solution is either send a request to unregister or modify codes to "skip" the process, would it be possible not to ```raise Exception("server registration failed")```? or have a way for users to re-register their devices?

cheers!

2020-03-31 19:06 UTC, pd0wm commented
If the private key is corrupt they need to contact comma. We need to manually remove the public from our database, otherwise you can't register the device with a different key. Otherwise you could just reregister with a new private key and take over someones account.

2020-03-31 19:09 UTC, merged