honda bosch disable radar
commaai/openpilot pull request #1459
Opened 2020-05-03 03:54 UTC by gregjhogan

the following steps disable the radar:
* enter extended diagnostic session
* send communication control message for disable tx and rx with suppress response bit
* send tester present with suppress response bit periodically to keep radar silent
  (radar wakes back up if it doesn't get a tester present message for a few seconds)

disabling an ecu in this manner is not unique to honda

2020-05-03 03:55 UTC, gregjhogan commented
looking for feedback ... I split this up between controlsd and carcontroller because:
* the initial disabling is similar to reading the VIN (request/response)
* the periodic message to keep it disabled is much simpler (fire and forget) and I would think we want as much as possible in the car specific interface

this doesn't feel great, is there a better approach? once the approach is agreed upon we can clean up things like the hard-coded CAN addr, etc...

2020-05-03 03:58 UTC, gregjhogan commented
we probably also need something that detects if the radar wakes back up which would disable openpilot

2020-05-03 07:01 UTC, csouers commented
> we probably also need something that detects if the radar wakes back up which would disable openpilot
one way to see if radar is back up is to check the counter on the radar's status frame (0x400 on bus 0 of black panda/uno). if it is different than the last time we saw it, then it must be alive. would need to setup a new can parser for that though. maybe camera outputs a connection state on the private can that we can check? is the radar's private can output totally silent with the disable?

2020-05-03 07:02 UTC, csouers commented
> we probably also need something that detects if the radar wakes back up which would disable openpilot

one way to see if radar is back up is to check the counter on the radar's status frame (0x400 on bus 0 of black panda/uno). if it is different than the last time we saw it, then it must be alive. would need to setup a new can parser for that though. maybe camera outputs a connection state on the private can that we can check? is the radar's private can output totally silent with the disable?

2020-05-03 07:40 UTC, csouers commented
bit 21 on 0x374 (f-can) goes high exclusively with the radar disconnected. I had an acc fault even after the reconnection and the bit went back low again after the reconnect. just a status bit for the control frames? is this bit low with op long?

2020-05-03 20:28 UTC, gregjhogan commented
we should be able to pick any radar message addr on the ACC bus that comes from the radar and ensure it is not present (ignoring the data)

I wish this all fit better into radard/radar_interface, but that is a lot more complicated if you want to prevent openpilot from sending any messages that the radar sends until after the radar is shut off

2020-05-11 21:21 UTC, pd0wm requested changes

2020-05-11 21:21 UTC, pd0wm commented on selfdrive/car/disable_ecu.py
> +  print(f"ecu disable {hex(ecu_addr)} ...")
change prints to cloudlog or remove them if only needed for testing

2020-05-11 21:21 UTC, pd0wm commented on selfdrive/car/honda/carcontroller.py
> +        can_sends.append([0x18DAB0F1, 0, b"\x02\x3E\x80\x00\x00\x00\x00\x00", 1 if CS.CP.isPandaBlack else 0])
Put radar debug addr in values.py

2020-05-11 21:21 UTC, pd0wm commented on selfdrive/car/disable_ecu.py
> +EXT_DIAG_REQUEST = b'\x10\x03'
Use constants from panda.uds

2020-05-11 21:21 UTC, pd0wm commented on selfdrive/car/honda/carcontroller.py
> +        can_sends.append([0x18DAB0F1, 0, b"\x02\x3E\x80\x00\x00\x00\x00\x00", 1 if CS.CP.isPandaBlack else 0])
Use constants from panda.uds

2020-05-11 21:21 UTC, pd0wm commented on selfdrive/controls/controlsd.py
> +  if CP.openpilotLongitudinalControl and CP.safetyModel in [car.CarParams.SafetyModel.hondaBoschGiraffe, car.CarParams.SafetyModel.hondaBoschHarness]:
why not check fingerprint in HONDA_BOSCH? Instead of safety mode?

2020-06-15 18:52 UTC, martinl commented
Would it make sense to make the ISO-TP queries more generic, for example create single and recurring query functions with car specific commands and query rate configurable from values.py 

I'm asking because we plan to query one OBDII PID value for some Subaru models after fingerprinting (related to country/market specific speed unit values) and I could not find a clean way to implement this query within existing framework (https://github.com/martinl/openpilot/blob/subaru-PR-test/selfdrive/car/obd_query.py)

2020-09-29 18:55 UTC, adeebshihadeh commented
Merged in the ECU disable script in 98fedff6b1f286c28a5beb12fd40b392b1d4ce65

2020-09-29 18:55 UTC, closed without merging