Cleanup include path,include from the root
commaai/openpilot pull request #20822
Opened 2021-05-04 19:22 UTC by deanlee

2021-05-04 20:26 UTC, adeebshihadeh commented
Nice, I'm fine with doing this one incrementally. Feel free to mark as ready for review whenever a good chunk of it is done.

2021-05-04 20:40 UTC, deanlee commented
format includes with google code style,sort by name, group by file type(c head file, c++head files, OP head files)

2021-05-04 20:44 UTC, adeebshihadeh commented
Hmm, I think this makes more sense: C/C++ standard libraries, external libs, then our headers. What do you think?

2021-05-04 20:57 UTC, adeebshihadeh commented
Also, let's leave phonelibs as is.

2021-05-04 21:12 UTC, deanlee commented
Yes, that would be better

2021-05-05 23:26 UTC, adeebshihadeh commented on installer/installer.c
> +#include <EGL/egl.h>
I'd consider these system libs more like external libs than standard libs

2021-05-05 23:27 UTC, adeebshihadeh commented on installer/updater/updater.cc
> +#include <EGL/egl.h>
same as above

2021-05-05 23:27 UTC, adeebshihadeh commented on selfdrive/boardd/boardd.cc
> +#include <libusb-1.0/libusb.h>
external lib

2021-05-05 23:27 UTC, adeebshihadeh commented on selfdrive/boardd/panda.h
> +#include <libusb-1.0/libusb.h>
external lib

2021-05-05 23:28 UTC, adeebshihadeh commented on selfdrive/camerad/cameras/camera_common.cc
> +#include <jpeglib.h>
external lib

2021-05-05 23:28 UTC, adeebshihadeh commented on selfdrive/camerad/cameras/camera_frame_stream.cc
> +#include <capnp/dynamic.h>
external lib

2021-05-06 04:03 UTC, adeebshihadeh commented on selfdrive/ui/replay/Unlogger.cc
> +// include the dynamic struct
doesn't make sense

2021-05-06 04:03 UTC, adeebshihadeh commented on selfdrive/ui/replay/FileReader.cc
>  #include "FileReader.h"
filereader?

2021-05-06 04:04 UTC, adeebshihadeh commented on selfdrive/ui/qt/widgets/offroad_alerts.h
> +#include <map>
stdlib above external libs

2021-05-06 04:04 UTC, adeebshihadeh commented on selfdrive/ui/qt/widgets/keyboard.h
> +#include <vector>
stdlib above external libs

2021-05-06 04:05 UTC, adeebshihadeh commented on selfdrive/ui/qt/spinner.h
> +#include <array>
stdlib above external libs

2021-05-06 04:05 UTC, adeebshihadeh commented on selfdrive/ui/qt/setup/setup.cc
> +#include <curl/curl.h>
not a stdlib

2021-05-06 04:05 UTC, adeebshihadeh commented on selfdrive/ui/qt/qt_window.h
> +#include <string>
stdlib above external libs

2021-05-06 04:05 UTC, adeebshihadeh commented on selfdrive/ui/qt/onroad.h
> +#include <map>
stdlib above external libs

2021-05-07 18:59 UTC, adeebshihadeh requested changes

2021-05-07 18:59 UTC, adeebshihadeh commented on selfdrive/locationd/ublox_msg.cc
> +#include "ublox_msg.h"
full path

2021-05-07 18:59 UTC, adeebshihadeh commented on selfdrive/logcatd/logcatd_systemd.cc
> +#include <systemd/sd-journal.h>
below stdlib

2021-05-07 18:59 UTC, adeebshihadeh commented on selfdrive/loggerd/tests/testraw.cc
> +#include <cstdio>
above external libs

2021-05-07 18:59 UTC, adeebshihadeh commented on selfdrive/modeld/models/driving.cc
> +#include "driving.h"
```suggestion
#include "selfdrive/modeld/models/driving.h"
```

2021-05-07 18:59 UTC, adeebshihadeh commented on selfdrive/hardware/eon/hardware.h
> +#include <cstdlib>
above external libs

2021-05-07 18:59 UTC, adeebshihadeh commented on selfdrive/locationd/locationd.h
> +#include <eigen3/Eigen/Dense>
external lib

2021-05-07 18:59 UTC, adeebshihadeh commented on selfdrive/modeld/models/commonmodel.cc
> +#include "commonmodel.h"
full path

2021-05-07 18:59 UTC, adeebshihadeh commented on selfdrive/modeld/transforms/transform.cc
> +#include "transform.h"
full path

2021-05-07 18:59 UTC, adeebshihadeh commented on selfdrive/sensord/sensors/bmx055_gyro.cc
> +#include "bmx055_gyro.h"
full path

2021-05-07 18:59 UTC, adeebshihadeh commented on selfdrive/sensord/sensors/bmx055_magn.cc
> +#include "bmx055_magn.h"
full path

2021-05-07 18:59 UTC, adeebshihadeh commented on selfdrive/sensord/sensors/file_sensor.cc
> +#include "file_sensor.h"
full path

2021-05-07 18:59 UTC, adeebshihadeh commented on selfdrive/sensord/sensors/i2c_sensor.cc
>  #include "i2c_sensor.h"
ful path

2021-05-07 18:59 UTC, adeebshihadeh commented on selfdrive/sensord/sensors/light_sensor.cc
> +#include "light_sensor.h"
full path

2021-05-07 18:59 UTC, adeebshihadeh commented on selfdrive/sensord/sensors/lsm6ds3_accel.cc
>  #include "lsm6ds3_accel.h"
full path

2021-05-07 18:59 UTC, adeebshihadeh commented on selfdrive/sensord/sensors/lsm6ds3_gyro.cc
> +#include "lsm6ds3_gyro.h"
full path

2021-05-07 18:59 UTC, adeebshihadeh commented on selfdrive/ui/paint.cc
> +#include "paint.h"
full path

2021-05-07 18:59 UTC, adeebshihadeh commented on selfdrive/ui/qt/offroad/networking.cc
> +#include "networking.h"
full path

2021-05-07 18:59 UTC, adeebshihadeh commented on selfdrive/ui/qt/offroad/wifiManager.cc
> +#include "wifiManager.h"
full path

2021-05-07 18:59 UTC, adeebshihadeh commented on selfdrive/ui/qt/setup/setup.cc
> +#include "setup.h"
full path

2021-05-07 18:59 UTC, adeebshihadeh commented on selfdrive/ui/qt/setup/wifi.cc
> +#include "wifi.h"
full path

2021-05-07 18:59 UTC, adeebshihadeh commented on selfdrive/ui/qt/spinner.cc
> +#include "spinner.h"
full path

2021-05-07 18:59 UTC, adeebshihadeh commented on selfdrive/ui/qt/widgets/input.cc
> +#include "input.h"
full path

2021-05-09 05:15 UTC, merged