Add support for Hyundai Tucson 2021
commaai/openpilot pull request #22863
Opened 2021-11-10 23:13 UTC by bluesforte

This is a working port for the Hyundai Tucson 2021. It has been tested by one of my clients on multiple long drives (3+hours each), and seems to be working well. I didn't do any lateral PID tune due to time constraints, but the default one handles pretty well.

Some notes:

    SteerRatio was determined empirically - 16 "felt" right after a few test drives.
    Car data (wheelbase, weight etc) was determined from the Hyundai website
    The Tucson cruise control appears not to turn on unless above ~20MPH, though does correctly stay on and allows for following cars even in stop-and-go traffic. May be able to be overridden somewhere in openpilot, but minimizing changes and don't want to have any impact on the safety model.
    Wish I had saved more test data while I had access to the car, but wasn't thinking ahead to the pull request :(. If I do get access again, I will grab the route data to add to test_routes.py.

Enjoy!

2021-11-11 00:12 UTC, adeebshihadeh commented on selfdrive/car/hyundai/values.py
> +  TUCSON_2021 = "HYUNDAI TUCSON_2021"
```suggestion
  TUCSON = "HYUNDAI TUCSON 2021"
```

2021-11-11 00:14 UTC, adeebshihadeh requested changes
Can you add the Tucson to docs/CARS.md? Once that's done and we get a test route, this should be good to merge.

2021-11-11 00:14 UTC, adeebshihadeh commented on selfdrive/car/hyundai/values.py
> +  }]
CAN fingerprinting is deprecated
```suggestion
```

2021-11-11 00:14 UTC, adeebshihadeh commented on selfdrive/car/hyundai/values.py
> +  CAR.TUCSON_2021: {
```suggestion
  CAR.TUCSON: {
```

2021-11-11 00:14 UTC, adeebshihadeh commented on selfdrive/car/hyundai/values.py
> +  "use_tcu_gears": set([CAR.KIA_OPTIMA, CAR.SONATA_LF, CAR.VELOSTER, CAR.TUCSON_2021]),
```suggestion
  "use_tcu_gears": set([CAR.KIA_OPTIMA, CAR.SONATA_LF, CAR.VELOSTER, CAR.TUCSON]),
```

2021-11-11 00:14 UTC, adeebshihadeh commented on selfdrive/car/hyundai/values.py
> +  CAR.TUCSON_2021: dbc_dict('hyundai_kia_generic', 'hyundai_kia_mando_front_radar'),
```suggestion
  CAR.TUCSON: dbc_dict('hyundai_kia_generic', None),
```

2021-11-11 00:14 UTC, adeebshihadeh commented on selfdrive/car/hyundai/interface.py
> +    elif candidate == CAR.TUCSON_2021:
```suggestion
    elif candidate == CAR.TUCSON:
```

2021-11-15 21:04 UTC, bluesforte commented
> 
> 
> Thanks for the car port, but we can't merge this without a test route. Are you sure you don't have any uploaded routes from the Tucson? If you still have the comma two or three, then the routes are still likely on the device.

Certainly understand.  I don't have access to the device anymore as it was an install for a friend's car and I'm away at the moment.  Next time I meet up with him I'll grab the latest routes off the device.  Just wanted to get this submitted here in case it helps anyone else.

2022-05-13 22:01 UTC, sshane commented
@bluesforte any updates on getting a test route?

2022-06-09 04:27 UTC, sshane commented
Moved to https://github.com/commaai/openpilot/pull/24791 to resolve conflicts, couldn't push. Thanks for the PR!

2022-06-09 04:27 UTC, closed without merging

2022-06-09 06:14 UTC, bluesforte commented
Ah sorry I never replied - yeah I wasn't able to get the car or device again to pull the logs :(.  Sorry.  Hopefully the PR is good enough for anyone else with a Tucson!

2022-06-09 06:26 UTC, sshane commented
@bluesforte Two quick questions, do you remember if the harness was Hyundai L? And when you say it doesn't engage below 20, you mean you can't engage it when you're physically under 20 mph, or that the set speed is limited to 20 mph? The latter is normal

2022-06-09 08:50 UTC, bluesforte commented
I remember when we had bought the harness we had gone with the one the site 'thought' might work (can't seem to find the page I remember from back then).  I do believe it was an L though.

Re: engaging, I meant the former actually.  In order to engage it the first time, the vehicle needed to be moving >~20mph.  After that, it'd do stop-and-go just fine.  It just wouldn't let you engage it from a stop or when moving too slowly.

2022-06-09 09:00 UTC, sshane commented
Yeah SCC normally won't let you engage under 5 mph without a lead, and 20 is the minimum set speed of cruise control (you engage at 6 mph, it speeds up to 20 for example).

There might be some qlogs I can check for this. Thanks for confirming the harness!

2022-06-09 21:06 UTC, bluesforte commented
> You had to be above 20 mph every time to engage, not just the first time?

Yep.  Min speed was indeed 20mph as well.  The part I specifically remember being strange was that the speed at which it engaged seemed to vary slightly, and I wasn't sure what it was based on.  Sometimes it'd engage at ~15mph, other times at ~20mph.  Didn't seem to be a fixed limit (though maybe it was a time-delayed gate or something).