fingerprint 2019 vw jetta sel
commaai/openpilot pull request #23299
Opened 2021-12-23 09:54 UTC by cyanet01

2021-12-23 18:00 UTC, VirtuallyChris commented
What’s the route this fingerprint came from?

2021-12-24 02:56 UTC, cyanet01 commented
Hello

186c80a9e18ac816|2021-12-22--22-42-56

That's the route name

II am new to this if not providing correct information
Please tell me where to get the route

Thanks


Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: Chris McCammon ***@***.***>
Sent: Thursday, December 23, 2021, 10:00 AM
To: commaai/openpilot
Cc: cyanet01; Author
Subject: Re: [commaai/openpilot] fingerprint 2019 vw jetta sel (PR #23299)


What’s the route this fingerprint came from?

—
Reply to this email directly, view it on GitHub<https://github.com/commaai/openpilot/pull/23299#issuecomment-1000453181>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AW3ICREM5YTF6LSRV3F2NWTUSNPTPANCNFSM5KUNDAWQ>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2021-12-24 04:50 UTC, jyoung8607 commented on selfdrive/car/volkswagen/values.py
> +      b'\xf1\x8704E906024C \xf1\x899970',
Move to 3rd on the list

2021-12-24 04:51 UTC, jyoung8607 commented on selfdrive/car/volkswagen/values.py
> +      b'\xf1\x875Q0959655AG\xf1\x890338\xf1\x82\x1314171231313500314611011630169333463100',
Move to 2nd on the list

2021-12-24 04:51 UTC, jyoung8607 commented on selfdrive/car/volkswagen/values.py
> +      b'\xf1\x875QM909144B \xf1\x891081\xf1\x82\x0521A10A01A1',
Remove; duplicate

2021-12-24 04:52 UTC, jyoung8607 commented on selfdrive/car/volkswagen/values.py
> +      b'\xf1\x875Q0907572P \xf1\x890682',
Move to 2nd on the list

2021-12-24 04:52 UTC, jyoung8607 requested changes
Can you help us out by adding these in sorted order? We try to keep them sorted to make it easier to find duplicates in the future.

2021-12-24 14:31 UTC, cyanet01 commented
Hello

I don’t believe there is any duplicate lines

Richard

From: Jason Young ***@***.***>
Sent: Thursday, December 23, 2021 8:52 PM
To: commaai/openpilot ***@***.***>
Cc: cyanet01 ***@***.***>; Author ***@***.***>
Subject: Re: [commaai/openpilot] fingerprint 2019 vw jetta sel (PR #23299)


@jyoung8607 commented on this pull request.

________________________________

In selfdrive/car/volkswagen/values.py<https://github.com/commaai/openpilot/pull/23299#discussion_r774871616>:

> @@ -319,10 +321,12 @@ class CAR:

       b'\xf1\x875QM909144C \xf1\x891082\xf1\x82\00521A00642A1',

       b'\xf1\x875QM909144C \xf1\x891082\xf1\x82\00521A10A01A1',

       b'\xf1\x875QN909144B \xf1\x895082\xf1\x82\00571A10A11A1',

+      b'\xf1\x875QM909144B \xf1\x891081\xf1\x82\x0521A10A01A1',

Remove; duplicate

—
Reply to this email directly, view it on GitHub<https://github.com/commaai/openpilot/pull/23299#pullrequestreview-839735197>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AW3ICRHXIBZE75U3PAEPEBDUSP36LANCNFSM5KUNDAWQ>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

2021-12-24 21:13 UTC, jyoung8607 commented
> Hello I don’t believe there is any duplicate lines 

Your EPS firmware was already on that list, second position. Automated CI checks later in the process will kick back duplicates, they're just not running for you yet as a new contributor.

I took the liberty of filing #23306 with your commit preserved along with the sorting/dedupe changes so we can go ahead and get you supported. Thank you for the data!

2021-12-24 21:25 UTC, closed without merging