GM skinny long pitch compensation
commaai/openpilot pull request #25485
Opened 2022-08-19 00:31 UTC by twilsonco

[This](https://github.com/commaai/openpilot/pull/25469), but without model-predicted pitch and contained in gm/carcontroller

2022-08-19 18:00 UTC, twilsonco commented
Route: c11fcb510a549332|2022-08-19--09-03-54--0

# Verification

Here we compare master with present and future pitch compensation on a couple steep steps of a hill, going up and down the steps.

Pitch compensation cuts speed error in half, and lowers acceleration error by 13%. 
Additionally, this eliminates the problem of `MAX_ACCEL` (2m/s^2) being insufficient for climbing steep hills; with pitch compensation op can accelerate up any hill the car can.

(In the future, when Comma has sufficiently verified the model predicted pitch, I'd like to [include future pitch in order to compensate for long actuator delay](https://github.com/commaai/openpilot/pull/25469), which, as you can see here, decreases speed and acceleration error by an additional 46% compared to when using instantaneous pitch. Compared to master, future pitch compensation reduces speed and acceleration error by 74% and 53% respectively, resulting in greater passenger comfort and improved vehicle efficiency.)

![pitch compare](https://user-images.githubusercontent.com/7284371/185678389-e590b559-6393-492b-8bc3-35e6f623e80a.png)

2022-10-28 00:18 UTC, sshane commented
@HaraldSchafer would Bolt long be helpful in verifying this? I can try to get that merged

2023-08-17 03:06 UTC, sshane commented
It's possible we need something similar to this for Toyotas to undo the accel compensation the PCM does, so we should try to make this as generic as possible.

2023-08-17 21:17 UTC, twilsonco commented
So something in between this and the [previous implementation](https://github.com/commaai/openpilot/pull/25469) that was unnecessarily couched inside of liveParams?

2023-08-17 21:24 UTC, adeebshihadeh commented
This isn't the large; blocking this on abstracting it out seems like premature optimization.

2023-08-17 22:07 UTC, sshane commented on selfdrive/car/gm/carcontroller.py
> +        accel += accel_g
any way you can remove the duplicate calculation?

2023-08-17 22:16 UTC, sshane requested changes

2023-08-17 22:16 UTC, sshane commented on selfdrive/car/gm/carcontroller.py
> +
```suggestion
```

2023-08-17 22:16 UTC, sshane commented on selfdrive/car/gm/carcontroller.py
> +        self.pitch.update(pitch)
Feels like the delta clip and the filter do similar things, any reason for both?

2023-08-17 22:16 UTC, sshane commented on selfdrive/car/gm/carcontroller.py
> +    accel = actuators.accel
use class variable so you don't need to set it when not an active control frame. check toyota/carcontroller

2023-08-17 22:16 UTC, sshane commented on selfdrive/car/gm/carcontroller.py
> +    self.pitch = FirstOrderFilter(0., 0.09 * 4, DT_CTRL * 4) # runs at 25 Hz
if we only use the filter, ensure that going from min to max pitch doesn't violate your selected rate limit above

2023-08-17 22:16 UTC, sshane commented on selfdrive/car/gm/carcontroller.py
> +          brake_accel = actuators.accel + accel_g * interp(CS.out.vEgo, BRAKE_PITCH_FACTOR_BP, BRAKE_PITCH_FACTOR_V)
if we change brake like this we probably should change gas

2023-08-17 22:16 UTC, sshane commented on selfdrive/car/gm/carcontroller.py
> +        accel += accel_g
use class variable

2023-10-28 00:43 UTC, simontheflutist commented
With a view towards https://github.com/commaai/openpilot/issues/30341, econd-order effects would change the calculation from `pitch` to `sin(pitch) cos(roll)`. I can't say for sure if it's necessary, but freeway ramps, which can have pronounced pitch and roll, come to mind.

2023-10-28 05:02 UTC, twilsonco commented
Thanks @simontheflutist.

Oops forgot to close this. This too will be superseded by #29659.

2023-11-19 20:31 UTC, twilsonco commented
Closed this in favor of #29659  which is now closed. Reopening

2023-12-20 04:23 UTC, twilsonco commented
I'll get Shanes's proposed changes done and a new test route so that this can be merged

2024-08-20 06:16 UTC, sshane commented
We've moved the car interfacing code to our [`opendbc`](https://github.com/commaai/opendbc) repository, which is now the new home for car ports and fingerprints. Please re-open your pull request against [`opendbc`](https://github.com/commaai/opendbc) at your convenience by using this command below. This will transform all changes under `selfdrive/car/` to `opendbc_repo/opendbc/car/`. Make sure you have initialized submodules beforehand and have checked out the latest `opendbc` commit.

```bash
PR_NUMBER=33045
curl -L https://github.com/commaai/openpilot/pull/$PR_NUMBER.patch | sed -e 's/selfdrive\/car/opendbc_repo\/opendbc\/car/g' | git apply -v --reject
```

Simply replace the PR number with your own. Once done, add the files, fix any conflicts, and open a new PR. Alternatively, you may start a new PR from scratch if that is easier for you.

2024-08-20 06:16 UTC, closed without merging

2024-09-20 05:34 UTC, sshane commented
If you would like to re-open, you can run our new [maneuver tool](https://github.com/commaai/openpilot/tree/master/tools/longitudinal_maneuvers) and share the before and after reports. Here are some examples of the report showing a clear and obvious improvement, enabling us to merge a new tune faster and easier:

https://github.com/commaai/opendbc/pull/1248

https://github.com/commaai/opendbc/pull/1260