VW MQB: Added support for APA racks to EPS configuration tool
commaai/openpilot pull request #25556
Opened 2022-08-25 18:33 UTC by calledit

APA steering racks use a different bit to represent whether the ECU should enable steering assist.
This change supports those APA steering racks.

Tested on a VW MK7 Golf sportsvan.

Testrun output:
```
root@localhost:/data/openpilot/selfdrive/debug$ ./vw_mqb_config.py enable
opening device 3e0031001251393031343235 0xddcc
connected

EPS diagnostic data

   Part No HW:   5Q0909143E 
   Part No SW:   5Q0909143K 
   SW Version:   2033
   Component:    MQB_PP_APA   
   Coding:       01000010005000
   ASAM Dataset: EV_SteerAssisVWBSMQBA
   Lane Assist:  DISABLED

EPS parameterization (per-vehicle calibration) data

   Version of system parameters:     51
   Vehicle type:                     9A
   Index of characteristic curve:    90
   Version of characteristic values: 40
   Version of memory map:            20

Attempting configuration update
   New coding:   01000011005000
EPS configuration successfully updated
```

2022-08-29 17:12 UTC, jyoung8607 commented
Thank you for doing this! Support for the APA racks is long overdue, and generalizing the byte/bit variables will be useful later for adding a third variant supporting the TRW racks in MQB-A0 vehicles.

Can we trouble you for a screenshot from VCDS or OBDeleven showing the backing ASAM dataset documentation for the bit we're flipping here? In the meantime, sometime in the next couple days I'll review in more detail and re-test to make sure nothing broken on my ZFLS rack.

2022-08-29 23:04 UTC, adeebshihadeh commented on selfdrive/debug/vw_mqb_config.py
> +  if coding_variant is None:
```suggestion
  elif odx_file == "EV_SteerAssisVWBSMQBA\x00\x00\x00\x00":
    coding_variant = "ZF2"
    coding_byte = 3
    coding_bit = 0

  else:
```

2022-08-30 09:54 UTC, calledit commented
> Can we trouble you for a screenshot from VCDS or OBDeleven showing the backing ASAM dataset documentation for the bit we're flipping here? In the meantime, sometime in the next couple days I'll review in more detail and re-test to make sure nothing broke in the support for my ZFLS rack with these changes.

I got the information about what bits does what from this website https://vagcode.info/components/8664d0e864943a58c78503a4194b9874.html seams like they got the information from a file called 5Q0-909-143.clb

2022-09-05 21:50 UTC, adeebshihadeh commented
@jyoung8607 look good to you?

2022-09-08 23:55 UTC, jyoung8607 requested changes

2022-09-08 23:55 UTC, jyoung8607 commented on selfdrive/debug/vw_mqb_config.py
> +    coding_variant = "ZF2"
```suggestion
    coding_variant = "APA"
```

2022-09-08 23:55 UTC, jyoung8607 commented on selfdrive/debug/vw_mqb_config.py
> +    assert(coding_variant in ('ZF', 'ZF2'))
```suggestion
    assert(coding_variant in ("ZF", "APA")) 
```

2022-09-08 23:56 UTC, jyoung8607 commented
> @jyoung8607 look good to you?

LGTM other than the proposed changes.

2022-09-09 18:20 UTC, merged