Multilang: add Turkish language
commaai/openpilot pull request #25765
Opened 2022-09-13 16:55 UTC by muhammetardayildiz

Merhaba! 👋 
I'm added the Turkish language to the device.

2022-12-13 09:19 UTC, sshane commented
Can you rebase your PR and add missing translations? I think we will merge without showing in the UI until we verify the translations to all fit the UI.

2022-12-13 12:01 UTC, muhammetardayildiz commented
Hello, let me check again and push the code.

2023-03-27 10:07 UTC, mustafadane requested changes

2023-03-27 10:07 UTC, mustafadane commented on selfdrive/ui/translations/main_tr.ts
> +        <translation>Girilen URL nin geçerli olduğundan ve cihazın internet bağlantısının olduğunu kontrol edin</translation>
Girilen URL nin geçerli olduğundan emin olun ve cihazın internet bağlantısının olduğunu kontrol edin

2023-03-27 10:07 UTC, mustafadane commented on selfdrive/ui/translations/main_tr.ts
> +        <translation>Zacznij od początku</translation>
Bastan basla

2023-03-27 10:07 UTC, mustafadane commented on selfdrive/ui/translations/main_tr.ts
> +        <translation>Yeni sürüm var ise eğer, cihazın bir sonraki başlatılışında çekilir.</translation>
Yeni surum bir sonraki guncelleyici ile beraber indirilecek.

2023-03-27 10:07 UTC, mustafadane commented on selfdrive/ui/translations/main_tr.ts
> +        <translation>Sürüm kodunu girin</translation>
Surum ismini girin

2023-03-27 10:07 UTC, mustafadane commented on selfdrive/ui/translations/main_tr.ts
> +        <translation>Kaldırmak istediğinden eminmisin?</translation>
typo: "emin misin"

2023-03-27 10:07 UTC, mustafadane commented on selfdrive/ui/translations/main_tr.ts
> +        <translation>Sürücü kamerasını kayıt et.</translation>
... kayit et ve yukle.

2023-03-27 10:07 UTC, mustafadane commented on selfdrive/ui/translations/main_tr.ts
> +        <translation>Sürücüye bakan kamera verisini yükleyin ve Cihazın algoritmasını geliştirmemize yardımcı olun.</translation>
algoritmasini -> surucu gozetim algoritmasini

2023-03-27 12:31 UTC, muhammetardayildiz commented
Hi @sshane New correct and stable translations added by @mustafadane

2023-04-19 07:15 UTC, sshane commented
@muhammetardayildiz can you merge them into your branch?

2023-08-01 01:37 UTC, sshane commented
If you make new commits onto your master branch with the changes and the font looks fine on-device we can merge this. Let me know if you'd like to go ahead without the updates commented here.

2023-08-17 04:44 UTC, sshane commented
@mustafadane please feel free to open a new PR to improve the translations! Merging as-is

2023-08-17 04:45 UTC, merged