Car interface: require fingerprint and FW to get params
commaai/openpilot pull request #26766
Opened 2022-12-12 06:11 UTC by sshane

2022-12-12 23:16 UTC, adeebshihadeh requested changes

2022-12-12 23:16 UTC, adeebshihadeh commented on selfdrive/car/tests/test_fw_fingerprint.py
> +        CP = interfaces[car_model][0].get_params(car_model, gen_empty_fingerprint(), [])
let's make a helper for this. name of the helper should make it obvious that the carParams are potentially wrong or incomplete

2022-12-13 00:22 UTC, sshane commented on selfdrive/car/interfaces.py
> +  def get_params(cls, candidate: str, fingerprint: Dict[int, Dict[int, int]], car_fw: List[car.CarParams.CarFw], experimental_long: bool = False):
i'll just make it all required

2023-01-10 05:36 UTC, adeebshihadeh commented
Any blockers on this?

2023-01-12 07:44 UTC, merged