ui/networking: remove call to clearLayout
commaai/openpilot pull request #29037
Opened 2023-07-19 12:46 UTC by deanlee

the `cabana/OpenPandaWidget` is still using clearLayout. so I haven't removed function clearLayout in this pr yet, just added a `[[deprecated]] `attribute to it.

2023-07-19 17:07 UTC, adeebshihadeh requested changes

2023-07-19 17:07 UTC, adeebshihadeh commented on selfdrive/ui/qt/util.h
>  void clearLayout(QLayout* layout);
let's move it to cabana instead, want to make sure nothing else in the openpilot ui uses it

2023-08-13 18:57 UTC, adeebshihadeh reviewed
Noticeable improvement! Want to take a stab at #29375 next?

2023-08-13 18:57 UTC, adeebshihadeh commented on selfdrive/ui/qt/offroad/networking.cc
> +  ssidLabel->style()->polish(ssidLabel);
this seems like it would be slow. we should probably get rid of this at some point?

2023-08-13 18:57 UTC, merged

2023-08-26 09:31 UTC, sshane commented
this breaks the consistent spacing when there's no icon

![image](https://github.com/commaai/openpilot/assets/25857203/a3428c03-7dc2-499d-be3a-09aedaa9917a)