Fix scons multithreaded build
commaai/openpilot pull request #29082
Opened 2023-07-21 20:39 UTC by maxime-desroches

2023-07-21 20:50 UTC, adeebshihadeh commented
Can we randomize the build order? That would catch this on the slow CI runners.

2023-07-21 20:52 UTC, adeebshihadeh commented
Looks like there's a `--random` flag.

2023-07-21 21:08 UTC, sshane commented
yeah there's more than just this:

```python
cd /home/batman/openpilot/selfdrive/controls/lib/lateral_mpc_lib && python3 lat_mpc.py
Traceback (most recent call last):
  File "/home/batman/openpilot/selfdrive/controls/lib/lateral_mpc_lib/lat_mpc.py", line 6, in <module>
    from common.realtime import sec_since_boot
  File "/home/batman/openpilot/common/realtime.py", line 10, in <module>
    from common.clock import sec_since_boot  # pylint: disable=no-name-in-module, import-error
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'common.clock'

Traceback (most recent call last):
  File "/home/batman/openpilot/tools/cabana/dbc/generate_dbc_json.py", line 5, in <module>
    from selfdrive.car.car_helpers import get_interface_attr
  File "/home/batman/openpilot/selfdrive/car/car_helpers.py", line 5, in <module>
    from common.params import Params
  File "/home/batman/openpilot/common/params.py", line 1, in <module>
    from common.params_pyx import Params, ParamKeyType, UnknownKeyName, put_nonblocking, put_bool_nonblocking # pylint: disable=no-name-in-module, import-error
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'common.params_pyx'
```

2023-07-21 21:12 UTC, adeebshihadeh commented
@maxime-desroches let's first write a good test that runs quickly on your workstation (with lots of cores). then we can run it in jenkins, which is similar to your workstation

2023-07-21 23:31 UTC, maxime-desroches commented
It catch some error

2023-07-22 00:02 UTC, adeebshihadeh requested changes
Let's make that change and fix the errors

2023-07-22 00:02 UTC, adeebshihadeh commented on Jenkinsfile
> +            sh "scons --clean && scons --no-cache --random -j42"
how about we do two passes: one normal build with lots of cores and add random to the second one?

2023-07-22 03:27 UTC, maxime-desroches commented
Ran over 35 times, that's all the bugs it could find

2023-07-22 04:20 UTC, adeebshihadeh approved these changes

2023-07-22 04:20 UTC, adeebshihadeh commented on Jenkinsfile
> +            sh "git lfs pull"
do we need lfs for the build?

2023-07-22 04:20 UTC, adeebshihadeh commented on selfdrive/controls/lib/lateral_mpc_lib/SConscript
> +source_lat = 'lat_mpc.py'
don't think this needs an intermediate variable

2023-07-22 04:20 UTC, adeebshihadeh commented on selfdrive/controls/lib/longitudinal_mpc_lib/SConscript
> +source_long = 'long_mpc.py'
same here

2023-07-22 04:57 UTC, merged