longitudinal_planner.py: cleaner variable assignment
commaai/openpilot pull request #29290
Opened 2023-08-09 07:15 UTC by eFiniLan

longitudinal_planner.py: cleaner variable assignment

2023-08-09 21:22 UTC, adeebshihadeh requested changes

2023-08-09 21:22 UTC, adeebshihadeh commented on selfdrive/controls/lib/longitudinal_planner.py
> +      accel_limits = accel_limits_turns = [ACCEL_MIN, ACCEL_MAX]
this isn't the same

2023-08-09 21:32 UTC, adeebshihadeh commented on selfdrive/controls/lib/longitudinal_planner.py
> +      accel_limits = accel_limits_turns = [ACCEL_MIN, ACCEL_MAX]
```suggestion
      accel_limits = [ACCEL_MIN, ACCEL_MAX]
      accel_limits_turns = [ACCEL_MIN, ACCEL_MAX]```

2023-08-09 22:17 UTC, merged

2023-08-10 02:05 UTC, eFiniLan commented on selfdrive/controls/lib/longitudinal_planner.py
> +      accel_limits = accel_limits_turns = [ACCEL_MIN, ACCEL_MAX]
got it, thanks adeeb!