UI: make wifi network sorting more stable
commaai/openpilot pull request #29376
Opened 2023-08-13 20:16 UTC by deanlee

resolve https://github.com/commaai/openpilot/issues/29375

2023-08-13 21:49 UTC, adeebshihadeh requested changes

2023-08-13 22:25 UTC, deanlee commented on selfdrive/ui/qt/offroad/wifiManager.h
> +inline int stretchLevel(unsigned int strength) { return std::clamp((int)round(strength / 33.), 0, 3); }
the build will fail with "multiple definition error" if no inline here.

2023-08-13 22:46 UTC, adeebshihadeh commented on selfdrive/ui/qt/offroad/wifiManager.h
> +inline int stretchLevel(unsigned int strength) { return std::clamp((int)round(strength / 33.), 0, 3); }
why?

2023-08-13 22:53 UTC, deanlee commented on selfdrive/ui/qt/offroad/wifiManager.h
> +inline int stretchLevel(unsigned int strength) { return std::clamp((int)round(strength / 33.), 0, 3); }
because it's not a class member function and is included by multiple .cc files.

2023-08-14 04:12 UTC, merged

2023-08-14 04:13 UTC, adeebshihadeh commented
Btw, seems like there's a bug where the currently connected network isn't highlighted in bold sometimes. Don't think it's a new thing though.

2023-08-14 06:04 UTC, deanlee commented
Think it's because the font weight we used for the connected network was 500(QFont::Medium), which makes it look little different from the QFont::Normal(400):

>     #ssidLabel[disconnected=false] {
>       font-weight: 500;
>     }

Bolding the connected network in https://github.com/commaai/openpilot/pull/29385