CI: use scons cache mount for building simulator and docs
commaai/openpilot pull request #29436
Opened 2023-08-16 22:53 UTC by jnewb1

2023-08-17 18:34 UTC, adeebshihadeh commented on tools/ci/Dockerfile.scons_cache
they should go in selfdrive/test/, which will be moved to tests/ pretty soon

2023-08-17 18:47 UTC, jnewb1 commented on tools/ci/Dockerfile.scons_cache
done

2023-08-17 21:24 UTC, jnewb1 commented
@adeebshihadeh this brings docs and sim builds to under 10 mins

2023-08-17 21:28 UTC, jnewb1 commented
Wait actually it looks like the moc files aren't cached every time so it's more like 11 sometimes, will look into that

2023-08-17 22:01 UTC, adeebshihadeh requested changes
docs is 12m and simulator is 11m. there is fundamentally no reason these are much slower than the `build all` job that took 5m. the goal is to make these as fast as we reasonably can

2023-08-21 06:41 UTC, jnewb1 commented
sim is down to 8:30 and docs is 7:30 now

2023-08-21 17:33 UTC, jnewb1 commented
Body and Panda aren't cached because git rev-parse fails in the container, since we don't copy the full git repo over. I'll handle that in a separate PR.

2023-08-21 22:08 UTC, adeebshihadeh approved these changes

2023-08-21 22:11 UTC, merged