scons: fix re-compiles MPCs every time
commaai/openpilot pull request #29485
Opened 2023-08-19 17:16 UTC by deanlee

remove invalid files from generate_files to fix this issue.

resolve https://github.com/commaai/openpilot/issues/29475

2023-08-20 22:10 UTC, adeebshihadeh commented
Something still isn't working right. I checked this out in a fully-built openpilot, and had to run twice before everything was built properly:
```
batman:lib$ scons -u -j8 .
scons: Entering directory `/home/batman/twopilot'
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
Retrieved `selfdrive/controls/lib/longitudinal_mpc_lib/c_generated_code/Makefile' from cache
Retrieved `selfdrive/controls/lib/longitudinal_mpc_lib/c_generated_code/main_long.c' from cache
Retrieved `selfdrive/controls/lib/longitudinal_mpc_lib/c_generated_code/acados_solver_long.h' from cache
Retrieved `selfdrive/controls/lib/longitudinal_mpc_lib/c_generated_code/acados_solver.pxd' from cache
Retrieved `selfdrive/controls/lib/longitudinal_mpc_lib/c_generated_code/long_model/long_expl_vde_adj.c' from cache
Retrieved `selfdrive/controls/lib/longitudinal_mpc_lib/c_generated_code/long_model/long_model.h' from cache
cd /home/batman/twopilot/selfdrive/controls/lib/longitudinal_mpc_lib && python3 long_mpc.py
Warning: Please note that the following versions of CasADi  are officially supported: 3.5.6 or 3.5.5 or 3.5.4 or 3.5.3 or 3.5.2 or 3.5.1 or 3.4.5 or 3.4.0.
 If there is an incompatibility with the CasADi generated code, please consider changing your CasADi version.
Version 3.6.3 currently in use.
scons: done building targets.
batman:lib$ scons -u -j8 .
scons: Entering directory `/home/batman/twopilot'
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
clang -o selfdrive/controls/lib/longitudinal_mpc_lib/c_generated_code/acados_ocp_solver_pyx.o -c -std=gnu11 -DSWAGLOG="\"common/swaglog.h\"" -g -fPIC -O2 -Wunused -Wshadow -Wno-unknown-warning-option -Wno-deprecated-register -Wno-register -Wno-inconsistent-missing-override -Wno-c99-designator -Wno-reorder-init-list -Wno-error=unused-but-set-variable -DSWAGLOG="\"common/swaglog.h\"" -Wno-#warnings -Wno-shadow -Wno-deprecated-declarations -I. -Ithird_party/acados/include -Ithird_party/acados/include/blasfeo/include -Ithird_party/acados/include/hpipm/include -Ithird_party/catch2/include -Ithird_party/libyuv/include -Ithird_party/json11 -Ithird_party/linux/include -Ithird_party/snpe/include -Ithird_party/mapbox-gl-native-qt/include -Ithird_party/qrcode -Ithird_party -Icereal -Iopendbc/can -I/home/batman/.pyenv/versions/3.11.4/include/python3.11 -I/home/batman/.pyenv/versions/3.11.4/lib/python3.11/site-packages/numpy/core/include selfdrive/controls/lib/longitudinal_mpc_lib/c_generated_code/acados_ocp_solver_pyx.c
selfdrive/controls/lib/longitudinal_mpc_lib/c_generated_code/acados_ocp_solver_pyx.c:8036:28: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
  if (((__pyx_v_c_mode[0]) == 'f')) {
       ~~~~~~~~~~~~~~~~~~~~^~~~~~
selfdrive/controls/lib/longitudinal_mpc_lib/c_generated_code/acados_ocp_solver_pyx.c:8036:28: note: remove extraneous parentheses around the comparison to silence this warning
  if (((__pyx_v_c_mode[0]) == 'f')) {
      ~                    ^     ~
selfdrive/controls/lib/longitudinal_mpc_lib/c_generated_code/acados_ocp_solver_pyx.c:8036:28: note: use '=' to turn this equality comparison into an assignment
  if (((__pyx_v_c_mode[0]) == 'f')) {
                           ^~
                           =
1 warning generated.
scons: done building targets.
batman:lib$ scons -u -j8 .
scons: Entering directory `/home/batman/twopilot'
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: `selfdrive/controls/lib' is up to date.
scons: done building targets.
```

2023-08-21 07:07 UTC, deanlee commented
it does need to rebuild again because the target of the `env.command` changed.
think this PR should have done its job, the cython warning is another issue.

2023-08-21 20:49 UTC, sshane commented
I had to run it three times before it stopped pulling from cache, second were these two:

```
Retrieved `selfdrive/controls/lib/lateral_mpc_lib/c_generated_code/acados_ocp_solver_pyx.o' from cache
Retrieved `selfdrive/controls/lib/longitudinal_mpc_lib/c_generated_code/acados_ocp_solver_pyx.o' from cache
```

2023-08-21 20:50 UTC, sshane commented
worked for me, no cache pulls on the third run

2023-08-21 22:24 UTC, sshane commented on selfdrive/controls/lib/lateral_mpc_lib/SConscript
>    f'{gen}/lat_model/lat_model.h',
```suggestion
  f'{gen}/lat_model/lat_model.h',
  f'{gen}/lat_cost/lat_cost.h.h',
```

It looks like they moved these three headers into `lat_cost.h` in the update from https://github.com/commaai/openpilot/pull/28821.

2023-08-21 22:24 UTC, sshane requested changes

2023-08-21 22:24 UTC, sshane commented on selfdrive/controls/lib/longitudinal_mpc_lib/SConscript
> +  f'{gen}/long_cost/long_cost.h',
Didn't check long, but probably also moved to one long_cost.h file

2023-08-21 22:26 UTC, sshane commented
Is there any scons option to throw an error on missing generated files?

2023-08-21 22:27 UTC, adeebshihadeh commented
related to that: https://github.com/commaai/openpilot/issues/29500

2023-08-22 03:52 UTC, deanlee commented
> Is there any scons option to throw an error on missing generated files?

there is a `TargetNotBuiltWarning`:
`SCons.Warnings.enableWarningClass(SCons.Warnings.TargetNotBuiltWarning)`

https://github.com/commaai/openpilot/issues/29500 enable all warnings, including this one.

2023-08-22 06:08 UTC, sshane commented on selfdrive/controls/lib/longitudinal_mpc_lib/SConscript
> +  f'{gen}/long_cost/long_cost.h',
ah I see you just missed the lateral one

2023-08-22 07:28 UTC, sshane commented
from a clean state, after a first compile, it still re-compiles these:

```python
batman@workstation-shane:~/openpilot$ scons -j32 
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
clang -o selfdrive/controls/lib/lateral_mpc_lib/c_generated_code/acados_ocp_solver_pyx.o -c -std=gnu11 -DSWAGLOG="\"common/swaglog.h\"" -g -fPIC -O2 -Wunused -Wshadow -Wno-unknown-warning-option -Wno-deprecated-register -Wno-register -Wno-inconsistent-missing-override -Wno-c99-designator -Wno-reorder-init-list -Wno-error=unused-but-set-variable -DSWAGLOG="\"common/swaglog.h\"" -Wno-#warnings -Wno-shadow -Wno-deprecated-declarations -I. -Ithird_party/acados/include -Ithird_party/acados/include/blasfeo/include -Ithird_party/acados/include/hpipm/include -Ithird_party/catch2/include -Ithird_party/libyuv/include -Ithird_party/json11 -Ithird_party/linux/include -Ithird_party/snpe/include -Ithird_party/mapbox-gl-native-qt/include -Ithird_party/qrcode -Ithird_party -Icereal -Iopendbc/can -I/home/batman/.pyenv/versions/3.11.4/include/python3.11 -I/home/batman/.pyenv/versions/3.11.4/lib/python3.11/site-packages/numpy/core/include selfdrive/controls/lib/lateral_mpc_lib/c_generated_code/acados_ocp_solver_pyx.c
clang -o selfdrive/controls/lib/lateral_mpc_lib/c_generated_code/acados_solver_lat.os -c -std=gnu11 -DSWAGLOG="\"common/swaglog.h\"" -DACADOS_WITH_QPOASES -g -fPIC -O2 -Wunused -Werror -Wshadow -Wno-unknown-warning-option -Wno-deprecated-register -Wno-register -Wno-inconsistent-missing-override -Wno-c99-designator -Wno-reorder-init-list -Wno-error=unused-but-set-variable -DSWAGLOG="\"common/swaglog.h\"" -Wno-unused -fPIC -I. -Ithird_party/acados/include -Ithird_party/acados/include/blasfeo/include -Ithird_party/acados/include/hpipm/include -Ithird_party/catch2/include -Ithird_party/libyuv/include -Ithird_party/json11 -Ithird_party/linux/include -Ithird_party/snpe/include -Ithird_party/mapbox-gl-native-qt/include -Ithird_party/qrcode -Ithird_party -Icereal -Iopendbc/can -Ithird_party/json11 selfdrive/controls/lib/lateral_mpc_lib/c_generated_code/acados_solver_lat.c
clang -o selfdrive/controls/lib/longitudinal_mpc_lib/c_generated_code/acados_solver_long.os -c -std=gnu11 -DSWAGLOG="\"common/swaglog.h\"" -DACADOS_WITH_QPOASES -g -fPIC -O2 -Wunused -Werror -Wshadow -Wno-unknown-warning-option -Wno-deprecated-register -Wno-register -Wno-inconsistent-missing-override -Wno-c99-designator -Wno-reorder-init-list -Wno-error=unused-but-set-variable -DSWAGLOG="\"common/swaglog.h\"" -Wno-unused -fPIC -I. -Ithird_party/acados/include -Ithird_party/acados/include/blasfeo/include -Ithird_party/acados/include/hpipm/include -Ithird_party/catch2/include -Ithird_party/libyuv/include -Ithird_party/json11 -Ithird_party/linux/include -Ithird_party/snpe/include -Ithird_party/mapbox-gl-native-qt/include -Ithird_party/qrcode -Ithird_party -Icereal -Iopendbc/can -Ithird_party/json11 selfdrive/controls/lib/longitudinal_mpc_lib/c_generated_code/acados_solver_long.c
clang -o selfdrive/controls/lib/longitudinal_mpc_lib/c_generated_code/acados_ocp_solver_pyx.o -c -std=gnu11 -DSWAGLOG="\"common/swaglog.h\"" -g -fPIC -O2 -Wunused -Wshadow -Wno-unknown-warning-option -Wno-deprecated-register -Wno-register -Wno-inconsistent-missing-override -Wno-c99-designator -Wno-reorder-init-list -Wno-error=unused-but-set-variable -DSWAGLOG="\"common/swaglog.h\"" -Wno-#warnings -Wno-shadow -Wno-deprecated-declarations -I. -Ithird_party/acados/include -Ithird_party/acados/include/blasfeo/include -Ithird_party/acados/include/hpipm/include -Ithird_party/catch2/include -Ithird_party/libyuv/include -Ithird_party/json11 -Ithird_party/linux/include -Ithird_party/snpe/include -Ithird_party/mapbox-gl-native-qt/include -Ithird_party/qrcode -Ithird_party -Icereal -Iopendbc/can -I/home/batman/.pyenv/versions/3.11.4/include/python3.11 -I/home/batman/.pyenv/versions/3.11.4/lib/python3.11/site-packages/numpy/core/include selfdrive/controls/lib/longitudinal_mpc_lib/c_generated_code/acados_ocp_solver_pyx.c
python3 tools/cabana/dbc/generate_dbc_json.py --out tools/cabana/dbc/car_fingerprint_to_dbc.json
Generated and written to tools/cabana/dbc/car_fingerprint_to_dbc.json
scons: done building targets.
batman@workstation-shane:~/openpilot$
```

2023-08-23 05:53 UTC, deanlee commented
> from a clean state, after a first compile, it still re-compiles these:
> 

It look like that SCons does not know about the dependency while the SharedLibrary compiled at the first time.  Scons will detect/update new dependencies In the second run, it will be ok on the third run.

run `scons -j20 --debug=explain` at second run:

> scons: rebuilding `selfdrive/controls/lib/lateral_mpc_lib/c_generated_code/acados_ocp_solver_pyx.c' because:
>            `third_party/acados/acados_template/acados_ocp_solver_pyx.pyx' changed
>            `third_party/acados/acados_template/acados_solver_common.pxd' changed
>            `selfdrive/controls/lib/lateral_mpc_lib/c_generated_code/acados_solver.pxd' is a new dependency
>            `/home/dean/.cache/pypoetry/virtualenvs/openpilot-j4J0Otje-py3.11/bin/cython' changed 
>  

This doesn't look like a bug, but a feature of scons. I haven't found a good way to solve this yet. I  recommend to merge this PR first. we can come back later to solve the dependency issue of SharedLibrary.

2023-08-23 22:31 UTC, sshane commented on selfdrive/controls/lib/lateral_mpc_lib/SConscript
> +  f'{gen}/lat_constraints/lat_constraints.h',
```suggestion
  f'{gen}/lat_constraints/lat_constraints.h',
  f'{gen}/lat_cost/lat_cost.h',
```

2023-08-23 22:31 UTC, sshane commented on selfdrive/controls/lib/longitudinal_mpc_lib/SConscript
> +
```suggestion
  f'{gen}/long_constraints/long_constraints.h',
  f'{gen}/long_cost/long_cost.h',
```

2023-08-23 22:31 UTC, sshane commented on selfdrive/controls/lib/longitudinal_mpc_lib/SConscript
> +
```suggestion
```

2023-08-23 22:33 UTC, sshane commented
I agree, we should fix the missing and moved headers first!

2023-08-23 22:43 UTC, merged