Subaru Pre-Global: Reverse driver torque signal for certain platforms
commaai/openpilot pull request #29782
Opened 2023-09-05 20:39 UTC by sunnyhaibin

- Use safety param assignment with panda flag for better maintainability

**Related**
- https://github.com/commaai/panda/pull/1648

2023-09-12 08:52 UTC, sshane commented on selfdrive/car/subaru/interface.py
> +      ret.safetyConfigs[0].safetyParam |= Panda.FLAG_SUBARU_PREGLOBAL_REVERSED_DRIVER_TORQUE
Are we sure about this?

```python
  CAR.FORESTER_PREGLOBAL: dbc_dict('subaru_forester_2017_generated', None),  # -1
  CAR.LEGACY_PREGLOBAL: dbc_dict('subaru_outback_2015_generated', None),  # 1 
  CAR.OUTBACK_PREGLOBAL: dbc_dict('subaru_outback_2015_generated', None),  # -1
  CAR.OUTBACK_PREGLOBAL_2018: dbc_dict('subaru_outback_2019_generated', None),  # -1
```

2023-09-12 08:54 UTC, sshane requested changes

2023-09-12 08:54 UTC, sshane commented on selfdrive/car/subaru/interface.py
> +      ret.safetyConfigs[0].safetyParam |= Panda.FLAG_SUBARU_PREGLOBAL_REVERSED_DRIVER_TORQUE
We should update `test_models` to check driver torque consistency between openpilot and panda.

2023-09-12 08:54 UTC, sshane requested changes

2023-11-21 20:45 UTC, jnewb1 commented
did this when I bumped panda: https://github.com/commaai/openpilot/commit/eed0ddc3b83dd88f0a927f3d5ad04d2260800948

2023-11-21 20:45 UTC, closed without merging