cabana: fix missing opendbc files
commaai/openpilot pull request #30555
Opened 2023-11-29 23:00 UTC by deanlee

fix https://github.com/commaai/openpilot/pull/30329?notification_referrer_id=NT_kwDNbHqwODE4NzU3OTA5MDoyNzc3MA#issuecomment-1800313473 :

> This removes a lot of DBCs from the list like radar DBCs and reference DBCs, used to be really useful.

after fix:

![2023-11-30_06-57](https://github.com/commaai/openpilot/assets/27770/d4571028-8404-444b-9ee2-427d3864f640)

2023-11-30 01:38 UTC, sshane commented
Something about the path looks wrong. Can we add a test that opens every DBC in Cabana and ensures there's no errors? There's a Honda DBC for example that would fail right now (solution is fixing it!)

![image](https://github.com/commaai/openpilot/assets/25857203/ea3202d5-be4a-4a21-8975-77b65f10cfc2)

2023-11-30 01:38 UTC, sshane requested changes
Something about the path looks wrong. Can we add a test that opens every DBC in Cabana and ensures there's no errors? There's a Honda DBC for example that would fail right now (solution is fixing it!)

![image](https://github.com/commaai/openpilot/assets/25857203/ea3202d5-be4a-4a21-8975-77b65f10cfc2)

2023-11-30 03:59 UTC, deanlee commented
> The path looks wrong. 

fixed

> Can we add a test that opens every DBC in Cabana and ensures there's no errors? There's a Honda DBC for example that would fail right now (solution is fixing it!). This would be the same as the opendbc parsing test.

will do it in another PR.

2023-12-01 04:46 UTC, merged

2023-12-01 04:46 UTC, sshane commented
ty!