Simulator: remove carla
commaai/openpilot pull request #30690
Opened 2023-12-12 01:37 UTC by jnewb1

carla has been replaced by metadrive in openpilot as it is much simpler and runs better on more computers

2023-12-12 01:46 UTC, adeebshihadeh requested changes

2023-12-12 01:46 UTC, adeebshihadeh commented on README.md
> +You can also run openpilot in simulation [with the metadrive simulator](tools/sim/README.md). This allows openpilot to drive around a virtual car on your Ubuntu machine. The whole setup should only t
it's stylized as MetaDrive

2023-12-12 01:46 UTC, adeebshihadeh commented on tools/sim/run_bridge.py
> +  if args.simulator == "metadrive":
let's remove the arg

2023-12-12 01:53 UTC, jnewb1 commented on tools/sim/run_bridge.py
> +  if args.simulator == "metadrive":
done

2023-12-12 01:53 UTC, jnewb1 commented on README.md
> +You can also run openpilot in simulation [with the metadrive simulator](tools/sim/README.md). This allows openpilot to drive around a virtual car on your Ubuntu machine. The whole setup should only t
done

2023-12-12 04:38 UTC, merged

2024-03-01 21:35 UTC, mimi89999 commented
Maybe the wiki should be updated too https://github.com/commaai/openpilot/wiki/Simulation ?