timed: get time and timezone from the modem
commaai/openpilot pull request #30867
Opened 2023-12-30 03:52 UTC by royjr

may fix #30702

2023-12-30 05:04 UTC, adeebshihadeh requested changes

2023-12-30 05:04 UTC, adeebshihadeh commented on system/timed.py
> +      continue
remove this, we want to always update it

2023-12-30 05:04 UTC, adeebshihadeh commented on release/files_tici
> -system/timezoned.py
revert the changes to timezoned. for this PR, I just want to add timed but not run it yet

2023-12-31 21:06 UTC, adeebshihadeh reviewed
Nice, this is looking pretty good. The last thing we need is an integration test that sets up each state we'll need to test (active SIM, missing SIM, and inactive SIM), runs `timed` for a cycle, then checks the time was set properly.

I can't immediately think of a way to test "inactive", but active and missing should be easy to test for with just AT commands.

2024-01-01 04:04 UTC, royjr commented
Tried a few different options that didn't work

#### AT+CFUN
```
comma@comma-bc60153f:/data/openpilot/system$ mmcli -m 0 --command AT+CFUN=0
response: ''
comma@comma-bc60153f:/data/openpilot/system$ mmcli -m 0 --command AT+QLTS=1
error: command failed: 'GDBus.Error:org.freedesktop.ModemManager1.Error.MobileEquipment.Unknown: Unknown error'
comma@comma-bc60153f:/data/openpilot/system$ mmcli -m 0 --command AT+CFUN=1
response: ''
comma@comma-bc60153f:/data/openpilot/system$ mmcli -m 0 --command AT+QLTS=1
response: '+QLTS: "2023/12/31,23:23:46-20,0"'
```

#### AT+COPS
```
comma@comma-bc60153f:/data/openpilot/system$ mmcli -m 0 --command AT+COPS=2
response: ''
comma@comma-bc60153f:/data/openpilot/system$ mmcli -m 0 --command AT+QLTS=1
response: ''
comma@comma-bc60153f:/data/openpilot/system$ mmcli -m 0 --command AT+QLTS=1
response: '+QIND: SMS DONE'
comma@comma-bc60153f:/data/openpilot/system$ mmcli -m 0 --command AT+QLTS=1
response: '+QLTS: "2023/12/31,23:37:53-20,0"'
```

This one seems to work
#### disable/enable

```
comma@comma-bc60153f:/data/openpilot$ mmcli -m 0 -d
successfully disabled the modem
comma@comma-bc60153f:/data/openpilot$ mmcli -m 0 --command AT+QLTS=1
response: '+QLTS: "2024/01/01,04:00:26-20,0"'
comma@comma-bc60153f:/data/openpilot$ mmcli -m 0 -e
successfully enabled the modem
comma@comma-bc60153f:/data/openpilot$ mmcli -m 0 --command AT+QLTS=1
response: '+QLTS: "2024/01/01,04:00:32-20,0"'
```

2024-01-01 19:19 UTC, adeebshihadeh commented
If it’s not straightforward to test like this, then let’s just do active and missing in the test for now, and I’ll manually check inactive before merging. I wouldn’t expect inactive to break if missing/active still work anyway.

2024-01-02 16:43 UTC, royjr commented
The `AT+QLTS=1` command doesn't seem to work when physically removing the sim.  Looks like this may be active sim dependant.

> with sim

```
comma@comma-bc60153f:/data/openpilot$ mmcli -m 0 --command AT+QLTS=1
response: '+QLTS: "2024/01/02,16:38:20-20,0"'
```

> with sim removed

```
comma@comma-bc60153f:/data/openpilot$ mmcli -m 0 --command AT+QLTS=1
error: command failed: 'GDBus.Error:org.freedesktop.ModemManager1.Error.MobileEquipment.Unknown: Unknown error'
```

2024-01-02 17:42 UTC, adeebshihadeh commented
Yea, for NITZ it has to be registered on the network. I'll move this to a draft for now.

2024-01-04 04:23 UTC, adeebshihadeh commented
I looked into it, and I don't think the original bounty target of getting time + timezone in all the specified states is really possible.  Given that, let's adjust the bounty.

We mainly care about time and timezone for two use cases: nav ETA and route names. Route naming is sort of "best effort", so the important one here is nav. Nav only works with GPS anyway, so we can rely on it for getting the time and timezone. We'll also keep your NITZ implementation to speedup some cases where you don't go onroad for a bit. Let's merge `timezoned` into your `timed`, then `timed` will get timezone from GPS coords, timezone from NITZ, and time from NITZ.

2024-01-11 05:15 UTC, royjr commented
Correctly failing over to GPS location when available and back on modem when car is turned off. Tests still pending.

```
Setting timezone based on modem
Setting timezone to Etc/GMT+5
Setting time to 2024-01-11 04:42:48
Thu 11 Jan 2024 04:42:48 AM UTC

Setting timezone based on modem
Setting timezone to Etc/GMT+5
Setting time to 2024-01-11 04:42:51
Thu 11 Jan 2024 04:42:51 AM UTC

Setting timezone based on GPS location
Setting timezone to America/New_York
Setting time to @1704948172
Thu 11 Jan 2024 04:42:52 AM UTC

Setting timezone based on GPS location
Setting timezone to America/New_York
Setting time to @1704948174
Thu 11 Jan 2024 04:42:54 AM UTC
```

2024-01-22 22:29 UTC, adeebshihadeh commented
Gonna give half the bounty value for this work ($150) since it's not finished and there's been no progress for a couple weeks. I'll take it over from here.

2024-01-22 22:29 UTC, closed without merging