Transferring to MapLibre
commaai/openpilot pull request #31185
Opened 2024-01-27 00:05 UTC by bongbui321

**Description**
Currently translate the codebase to maplibre-qt already. 

**Verification**
Trying to build maplibre-qt, but is currently facing an issue similar to [this](https://github.com/maplibre/maplibre-native-qt/issues/76)

Will  test using `map_renderer.py`, not sure if this is a good way to test this?

2024-01-27 01:25 UTC, adeebshihadeh commented
> Will test using `map_renderer.py`, not sure if this is a good way to test this? Probably better test with replay

I'd probably start with replaying the demo route and just checking the map generally works in the UI, then test the map renderer. See here for getting setup: https://github.com/commaai/openpilot/tree/master/selfdrive/navd#development

2024-01-27 17:54 UTC, adeebshihadeh commented
What does full desktop support mean? We can't make this work with 5.12?

2024-01-27 18:10 UTC, bongbui321 commented
From the [README](https://github.com/maplibre/maplibre-native-qt), it is "fully supported on desktop platform" which I think on the OSes. I think it is fine since Agnos is mainly based on Ubuntu 20.04? 

anything below 5.15 doesn't support `Location` which I think is used for getting routes and positions. I think we can kind of work around this if we have our own fork. I haven't dive deep into the codebase, but it might be possible

2024-01-27 18:12 UTC, adeebshihadeh commented
Ah, if there's lot of hacks, then I don't think this is worth it. We'll be switching to 24.04 in a few months when it's out anyway. If you confirm, there are lots of hacks to get it working on our Qt, then we can just keep this bounty locked to you until the switch.

2024-01-28 08:54 UTC, bongbui321 commented
Okay, I think it is possible to work with 5.12. I made a small [PR](https://github.com/maplibre/maplibre-native-qt/pull/107) that makes it compilable with Qt 5.12. We don't need `Location` since we are getting position and location from cereal already. so we can disable the `Location` option with 
`cmake -DMLN_QT_WITH_LOCATION=OFF ..`

I was trying to test with the demo route of `replay` but that one doesn't seem to have map enabled, is there a different route that I can test with?. 
I also test with `map_renderer.py` and got a `segfault`. I tried to implement the exact same function in `.c` here is the file: 
 [test.txt](https://github.com/commaai/openpilot/files/14075441/test.txt) and it works just fine with no `segfault`, not entirely sure why it doesn't work for python implementation

2024-01-29 22:58 UTC, adeebshihadeh commented
> Okay, I made it work with 5.12. I made a small [PR](https://github.com/maplibre/maplibre-native-qt/pull/107) that makes it compilable with Qt 5.12. We don't need `Location` since we are getting position and location from cereal already. so we can disable the `Location` option with `cmake -DMLN_QT_WITH_LOCATION=OFF ..`
> 
> I was trying to test with the demo route of `replay` but that one doesn't seem to have map enabled, is there a different route that I can test with?. I also test with `map_renderer.py` and got a `segfault`. I tried to implement the exact same function in `.c` here is the file: [test.txt](https://github.com/commaai/openpilot/files/14075441/test.txt) and it works just fine with no `segfault`, not entirely sure why it doesn't work for python implementation

Nice! I see that got merged already. 

Testing it doesn't require a route with nav enabled; the map will be available if you have everything setup, such as a token.

2024-01-29 23:54 UTC, bongbui321 commented
@adeebshihadeh it seems to work perfectly now, do you need me to upload the compiled library or do you want me to write a shell to download and set it up automatically. Here is a snapshot of the demo with maplibre. Still figuring out how to record videos :)
![image](https://github.com/commaai/openpilot/assets/47828508/57507fd7-e57e-47e7-a902-17992c12c37b)

2024-01-30 00:02 UTC, adeebshihadeh commented
Great. We always want a script to build the `third_party` dependencies so that they're reproducible, then you can check them in once that's done. This one is a good example https://github.com/commaai/openpilot/blob/master/third_party/acados/build.sh

2024-01-30 01:33 UTC, adeebshihadeh commented
@mitchellgoffpc any validation you want to do before merging this?

2024-01-30 04:34 UTC, bongbui321 commented
@adeebshihadeh added the build script

> I also test with map_renderer.py and got a segfault. I tried to implement the exact same function in .c here is the file: [test.txt](https://github.com/commaai/openpilot/files/14075441/test.txt) and it works just fine with no segfault, not entirely sure why it doesn't work for python implementation

The UI works fine, if possible you can test it out just to make sure I didn't introduce any bug, but the `map_renderer.py` doesn't seem to work. I created the same code in `.c` file as above and it doesn't have any segfault, I'm not sure why it doesn't work

2024-01-30 04:49 UTC, mitchellgoffpc commented
> @mitchellgoffpc any validation you want to do before merging this?

Yeah we should verify that it doesn't impact model performance, will run those tests tomorrow morning.

2024-01-30 23:25 UTC, adeebshihadeh requested changes
I haven't run it yet, but it looks pretty good! I left a few minor things to cleanup.

2024-01-30 23:25 UTC, adeebshihadeh commented on third_party/maplibre-native-qt/build.sh
> +git submodule update --depth=1 --recursive --init
this should be pinned to a specific commit on their repo. in this case, likely the commit where they merged your fix

2024-01-30 23:25 UTC, adeebshihadeh commented on third_party/maplibre-native-qt/build.sh
> +mkdir -p build && cd build
```suggestion
mkdir -p build
cd build
```

2024-01-30 23:25 UTC, adeebshihadeh commented on third_party/maplibre-native-qt/build.sh
> +#build
```suggestion
# build
```

2024-01-30 23:25 UTC, adeebshihadeh commented on third_party/maplibre-native-qt/build.sh
> +ARCHNAME="x86_64"
can you add support for aarch64 for the comma 3X? I can handle testing it

2024-01-31 01:52 UTC, adeebshihadeh commented
CI is passing now, but there's some issues building it on device (CMake is too old and it's missing `libqconnmanbearer.so`). I'll look into those when I get a chance.

2024-01-31 04:53 UTC, adeebshihadeh commented
Got it working on the comma 3X, and all the tests pass except navModel replay. I'll update the refs once you verify @mitchellgoffpc.

2024-02-01 21:24 UTC, mitchellgoffpc commented
@adeebshihadeh lgtm, model behavior appears to be pretty much identical

2024-02-01 21:37 UTC, merged

2024-02-07 16:37 UTC, SurferSD commented
This merge (transfer to MapLibre) breaks OP tools build (PJ plugin) on the Apple platform due to missing Darwin library files.

2024-02-07 17:02 UTC, bongbui321 commented
@SurferSD please use the build script, and i think its better to open an issue rather than commenting on Pr since it mostly relates to development