Generate UI screenshots in different states
commaai/openpilot pull request #31996
Opened 2024-03-25 09:52 UTC by thenhnn

# States

- [x] Home screen with prime
- [x] Home screen without prime
- [x] Device settings
- [x] Network settings (including Advanced)
- [x] Toggles settings
- [x] Software settings
- [x] Driver camera
- [x] Update
- [x] All offroad alerts 
- [x] All onroad alerts
- [x] Keyboard
- [x] Keyboard with numbers
- [x] Onroad
- [x] Onroad w/ map
- [x] Onroad w/ sidebar 
- [x] Onroad engaged
- [x] Onroad overriding
- [x] Experimental mode confirmation dialog

2024-03-27 12:46 UTC, thenhnn commented
@adeebshihadeh I'm thinking about html report.

GitHub pages requires making write-access for special repo or branch, according to #31198, you don't want to.
GitHub actions *[can](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/)* create job summaries (which is cool, and it will be more convient than clickable link IMO), but there's no way to upload images in job summary, only image links are supported. Maybe use some CDN? GitHub actions artifacts are zipped, so we can't include them in summaries. (maybe we can exploit this, AFAIK, upload-artifact makes ZIP archive on client, so we can probably replace that with image, but this is very hacky)

What do you think?

2024-03-27 12:48 UTC, thenhnn commented
I can work on that in separate PR, to make things simpler.

2024-03-28 06:42 UTC, thenhnn commented
I will work on reports in separate PR.

2024-03-29 06:42 UTC, thenhnn commented
@jnewb1 can you review this one?

2024-03-30 18:17 UTC, thenhnn commented
@adeebshihadeh @jnewb1 This PR is pretty done, currently I'm thinking where to upload screenshots, to show them in report. I will create Draft PR when PoC will be ready.

2024-04-01 16:42 UTC, jnewb1 commented
it takes 10 minutes to create this report now in CI, can we parallelize this?

```
Ran 20 tests in 559.315s
creating html report

OK
```

2024-04-01 16:45 UTC, jnewb1 commented
html report is also empty

2024-04-01 17:17 UTC, thenhnn commented
> html report is also empty, and a bunch of the screenshots are just the terms and conditions (ex: homescreen.png) ![homescreen](https://private-user-images.githubusercontent.com/9648890/318507623-28a65d63-7049-4290-a785-842c369b4002.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5OTA1NTEsIm5iZiI6MTcxMTk5MDI1MSwicGF0aCI6Ii85NjQ4ODkwLzMxODUwNzYyMy0yOGE2NWQ2My03MDQ5LTQyOTAtYTc4NS04NDJjMzY5YjQwMDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDFUMTY1MDUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzkwMzI1MjU4ZGMzOWQwNTQwOWQzOGNhZjgzMzJkYzFhNDRiNzNhYjNkZGUzMjQzZDJmMDFmNDJiNzg2Zjg4OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dmx6lNdBmAk96B8NRnWoHMToviZvFusTUbOj1snrIH0)

Strange, works on my machine.

Should I make HTML report there and CI pages/[job summaries](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/) in this PR, or I should separate pages into it's own PR?

2024-04-01 17:43 UTC, jnewb1 commented
> > html report is also empty, and a bunch of the screenshots are just the terms and conditions (ex: homescreen.png) ![homescreen](https://private-user-images.githubusercontent.com/9648890/318507623-28a65d63-7049-4290-a785-842c369b4002.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5OTA1NTEsIm5iZiI6MTcxMTk5MDI1MSwicGF0aCI6Ii85NjQ4ODkwLzMxODUwNzYyMy0yOGE2NWQ2My03MDQ5LTQyOTAtYTc4NS04NDJjMzY5YjQwMDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDFUMTY1MDUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzkwMzI1MjU4ZGMzOWQwNTQwOWQzOGNhZjgzMzJkYzFhNDRiNzNhYjNkZGUzMjQzZDJmMDFmNDJiNzg2Zjg4OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dmx6lNdBmAk96B8NRnWoHMToviZvFusTUbOj1snrIH0)
> 
> Strange, works on my machine.
> 
> Should I make HTML report and CI pages/[job summaries](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/) in this PR, or I should separate pages into another PR?

the html report is automatically created and uploaded as a CI artifact

2024-04-01 17:46 UTC, thenhnn commented
> > > html report is also empty, and a bunch of the screenshots are just the terms and conditions (ex: homescreen.png) ![homescreen](https://private-user-images.githubusercontent.com/9648890/318507623-28a65d63-7049-4290-a785-842c369b4002.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5OTA1NTEsIm5iZiI6MTcxMTk5MDI1MSwicGF0aCI6Ii85NjQ4ODkwLzMxODUwNzYyMy0yOGE2NWQ2My03MDQ5LTQyOTAtYTc4NS04NDJjMzY5YjQwMDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDFUMTY1MDUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzkwMzI1MjU4ZGMzOWQwNTQwOWQzOGNhZjgzMzJkYzFhNDRiNzNhYjNkZGUzMjQzZDJmMDFmNDJiNzg2Zjg4OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dmx6lNdBmAk96B8NRnWoHMToviZvFusTUbOj1snrIH0)
> > 
> > 
> > Strange, works on my machine.
> > Should I make HTML report and CI pages/[job summaries](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/) in this PR, or I should separate pages into another PR?
> 
> the html report is automatically created and uploaded as a CI artifact

Right, but it's not clickable link, it's ZIP archive that needs to be downloaded and unpacked.

2024-04-01 17:49 UTC, jnewb1 commented
> Right, but it's not clickable link, it's ZIP archive that needs to be downloaded and unpacked.

it doesn't need to be a clickable link in this PR, but it should still work when downloaded. currently it's an empty html

2024-04-01 18:33 UTC, thenhnn commented
> @jnewb1: and the rest are only run manually

How to do that? I can create separate "Create Full UI Report" job, how to make it disabled by default?

2024-04-01 18:36 UTC, jnewb1 commented
> How to do that? I can create separate "Create Full UI Report" job, how to make it disabled by default?

just put some of the cases behind a cmd flag, such as "--all"

2024-04-01 18:39 UTC, thenhnn commented
Hmm, for some reason `HasAcceptedTerms` and `CompletedTrainingVersion` works on my PC, but not on CI...

2024-04-01 19:09 UTC, thenhnn commented
@jnewb1 I created new workflow `full_ui_test` that can be manually invoked, if I understand `workflow_dispatch` correctly.

2024-05-03 12:55 UTC, thenhnn commented
Any chance to get this merged?

2024-05-19 00:17 UTC, adeebshihadeh requested changes
I glanced over this, and there's a lot of brittle code in `test_ui/run.py`, such as specific coordinates and copy/pasted constants. Before we add all this brittle code, I want to make sure it has value, and to evaluate that, I think we need to start getting the report published in a nice way. 

I edited the bounty and reduced the scope to just getting the existing report published in a nice way. Bounty is still locked to you. Once that's in, I'll probably setup a new bounty to get more states in, and you can reuse this code for that.

See updated bounty description: https://github.com/commaai/openpilot/issues/31007

2024-05-19 00:17 UTC, closed without merging