camerad: OS HDR
commaai/openpilot pull request #32112
Opened 2024-04-05 22:37 UTC by ZwX1616

2024-04-10 22:02 UTC, adeebshihadeh requested changes
The debayer kernel is getting super messy. It's really important that as a project we strictly improve. Some general things that would improve the kernel a lot:
* less magic numbers
* more descriptive names and comments
* more arguments instead of ifdefs, e.g. define the color correction values in `SensorInfo` and pass them in

2024-04-11 00:15 UTC, ZwX1616 commented on system/camerad/sensors/sensor.h
> +  bool bggr;
well there'll only be two really, like odd and even, at least in our case

2024-04-17 20:16 UTC, adeebshihadeh requested changes
Looks a lot better now but this is still pretty massive. It's OS HDR + what should be a no-op refactor. Let's split those two up. Also, I see the test is deleted; how did you verify that it's no-op on AR/OX?

2024-04-17 20:16 UTC, adeebshihadeh commented on system/camerad/cameras/camera_common.h
> +typedef struct AutoExposureRect {
this is just a "rect". move to common/util.h?

2024-04-19 20:44 UTC, merged