CI/Simulator: Drive a loop in metadrive
commaai/openpilot pull request #32308
Opened 2024-04-28 09:07 UTC by bongbui321

Resolve [#30694](https://github.com/commaai/openpilot/issues/30694)

Currently, the simulator will fail when it tries to cross lane (can try to run the simulator normally, and disengage), and can change the track_size for CI testing.

Depends on: https://github.com/metadriverse/metadrive/pull/710

Will try to add some more testing cases, and cleanup the PR when I have more time, gonna be busy upcoming weeks

2024-05-19 00:47 UTC, adeebshihadeh commented
>   ~- [ ] maybe more test cases (lead car, etc)~ traffic is extremely expensive even running locally with decent gpu

A super reliable test that only tests one thing is way more valuable than a fancy one that's flaky :)

2024-05-20 04:28 UTC, bongbui321 commented
Tried running locally with `pytest tools/sim/tests/test_metadrive_bridge.py --time_done=600`. can modify to run the loop as long as you want it to be

2024-05-20 04:41 UTC, adeebshihadeh requested changes
Took me a few attempts to get this running locally. Seems like there were two main issues:

```
UserWarning: PyOpenCL compiler caching failed with an exception:
[begin exception]
Traceback (most recent call last):
  File "/home/batman/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pyopencl/cache.py", line 495, in create_built_program_from_source_cached
    _create_built_program_from_source_cached(
  File "/home/batman/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pyopencl/cache.py", line 417, in _create_built_program_from_source_cached
    prg.build(options_bytes, [devices[i] for i in to_be_built_indices])
  File "/home/batman/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pyopencl/__init__.py", line 772, in program_build
    compiler_output("%s succeeded, but resulted in non-empty logs:\n%s"
  File "/home/batman/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pyopencl/__init__.py", line 273, in compiler_output
    warn("Non-empty compiler output encountered. Set the "
pyopencl.CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
[end exception]
```

and 

```
State:
Ignition: True Engaged: False


State:
Ignition: True Engaged: False
    Waiting for CAN messages...
logcatd proclogd modeld ui soundd locationd calibrationd torqued controlsd deleter navd paramsd plannerd radard thermald statsd
logcatd proclogd modeld ui soundd locationd calibrationd torqued controlsd deleter navd paramsd plannerd radard thermald statsd
Process bridge:
Traceback (most recent call last):
  File "/home/batman/.pyenv/versions/3.11.4/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/batman/.pyenv/versions/3.11.4/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/dev/shm/openpilot/threepilot/openpilot/tools/sim/bridge/common.py", line 71, in bridge_keep_alive
    self._run(q)
  File "/dev/shm/openpilot/threepilot/openpilot/tools/sim/bridge/common.py", line 197, in _run
    self.print_status()
  File "/dev/shm/openpilot/threepilot/openpilot/tools/sim/bridge/common.py", line 88, in print_status
    print(
BlockingIOError: [Errno 11] write could not complete without blocking

modeld init
setting up CL context
CL context ready; loading model
Onnx available providers:  ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'AzureExecutionProvider', 'CPUExecutionProvider']
Onnx selected provider:  [('CUDAExecutionProvider', {'cudnn_conv_algo_search': 'DEFAULT'})]
logcatd proclogd modeld ui soundd locationd calibrationd torqued controlsd deleter navd paramsd plannerd radard thermald statsd
Onnx using  ['CUDAExecutionProvider', 'CPUExecutionProvider']
ready to run onnx model {'input_imgs': [1, 12, 128, 256], 'big_input_imgs': [1, 12, 128, 256], 'desire': [1, 100, 8], 'traffic_convention': [1, 2], 'lateral_control_params': [1, 2], 'prev_desired_curv': [1, 100, 1], 'features_buffer': [1, 99, 512]}
models loaded, modeld starting
logcatd proclogd modeld ui soundd locationd calibrationd torqued controlsd deleter navd paramsd plannerd radard thermald statsd
logcatd proclogd modeld ui soundd locationd calibrationd torqued controlsd deleter navd paramsd plannerd radard thermald statsd
logcatd proclogd modeld ui soundd locationd calibrationd torqued controlsd deleter navd paramsd plannerd radard thermald statsd
```

2024-05-20 04:41 UTC, adeebshihadeh commented on .github/workflows/tools_tests.yaml
> +                        CI=1 pytest tools/sim/tests/test_metadrive_bridge.py --time_done=90 -W ignore::pyopencl.CompilerWarning"
needed to add "-W ignore::pyopencl.CompilerWarning" when running locally as well. let's put this directly in the code so it doesn't need to be specified on the command line (or fix the warning)

2024-05-20 04:41 UTC, adeebshihadeh commented on tools/sim/tests/conftest.py
> +  parser.addoption("--time_done", action="store", default=60, type=int, help="Seconds to run metadrive drive")
call this "test_duration"

2024-05-20 04:41 UTC, adeebshihadeh commented on tools/sim/tests/test_metadrive_bridge.py
> +  @pytest.fixture(autouse=True)
is this decorator necessary for setup_class?

2024-05-20 04:41 UTC, adeebshihadeh commented on tools/sim/bridge/metadrive/metadrive_process.py
> +      out_of_lane = env.vehicle.on_broken_line or env.vehicle.on_yellow_continuous_line or env.vehicle.on_white_continuous_line or env.vehicle.crash_sidewalk
any way to check "vehicle in lane" or another simple check? looks like we might have to keep adding conditions for this one

2024-05-21 23:07 UTC, adeebshihadeh requested changes
Had no issues running locally now. However, it's easy to make the test pass when it shouldn't with this patch. I think adding a check on distance (based on the time) should be enough. Other than that, seems good to go.

```
diff --git a/tools/sim/bridge/common.py b/tools/sim/bridge/common.py
index 64407143f..997a2e0cf 100644
--- a/tools/sim/bridge/common.py
+++ b/tools/sim/bridge/common.py
@@ -184,6 +184,7 @@ Ignition: {self.simulator_state.ignition} Engaged: {self.simulator_state.is_enga
       brake_out = brake_op if self.simulator_state.is_engaged else brake_manual
       steer_out = steer_op if self.simulator_state.is_engaged else steer_manual

+      throttle_out = 0.
       self.world.apply_controls(steer_out, throttle_out, brake_out)
       self.world.read_state()
       self.world.read_sensors(self.simulator_state)
```

2024-05-21 23:20 UTC, bongbui321 commented
>  think adding a check on distance (based on the time) should be enough

Was thinking of adding that test for the Metadrive run on GHA since for this one we could still visually see it's moving

2024-05-22 17:04 UTC, merged

2024-05-22 17:04 UTC, adeebshihadeh commented
Nice work! Looking forward to getting this in CI.