remove unittest test_models
commaai/openpilot pull request #32465
Opened 2024-05-18 06:33 UTC by cl0cks4fe

- removes unittest from `openpilot.selfdrive.car.tests.test_models.py`
- switches `tools/car_porting/test_car_model.py` to inherit from `test_models.py`

not totally ideal but keeps use

2024-05-18 17:23 UTC, cl0cks4fe commented
skips base class tests but so does `test_models`

2024-05-18 21:56 UTC, adeebshihadeh requested changes

2024-05-18 21:56 UTC, adeebshihadeh commented on tools/car_porting/test_car_model.py
> +test_route = CarTestRoute(route_or_segment_name.route_name.canonical_name, car, segment=segment_num)
all this stuff runs at import time now. it should only be run if we're running this script

2024-05-18 21:56 UTC, adeebshihadeh commented on tools/car_porting/test_car_model.py
> +route = os.getenv('ROUTE')
this is now harder to use without the argparser. can we bring that back?

2024-05-19 18:48 UTC, cl0cks4fe commented
@adeebshihadeh because of pytest discovery, lose something similar to `loadTestsFromTestCase` to run this as script, i'll revisit

2024-05-19 18:48 UTC, closed without merging