Replace setproctitle dependency
commaai/openpilot pull request #32666
Opened 2024-06-08 19:18 UTC by markypizz

First PR. Still a work-in-progress, curious if I'm trending in the right direction, will be able to clean this up in the next day or so, if so. Most tests are failing, not sure if it's just my environment or not. Thanks for your consideration!

**Description**

Replace `setproctitle` dependency with our own small helper

**Verification**

WIP. Testing via `pytest`

2024-06-08 19:46 UTC, adeebshihadeh requested changes
Welcome, and yeah this is the right general direction.

Tests are failing because there's still a `setproctitle` import. CI green check mark + verify the title shows up in `htop` is enough validation for this change

2024-06-08 19:46 UTC, adeebshihadeh commented on common/setproctitle.py
> +    pid = os.getpid()
we use two space indentation

2024-06-08 19:46 UTC, adeebshihadeh commented on common/setproctitle.py
> +    proctitle = run_cmd([f"cat /proc/{pid}/comm"])
make sure to check if we're on linux

2024-06-09 00:30 UTC, markypizz commented
Addresses https://github.com/commaai/openpilot/issues/32660 . Let me know of anything else to change. Thanks!

```openpilot-py3.11vscode ➜ /workspaces/ubuntu $ ps -a
    PID TTY          TIME CMD
  37224 pts/0    00:00:01 poetry
  49515 pts/1    00:00:15 loggerd
  49533 pts/1    00:00:15 loggerd
  95648 pts/1    00:00:00 python3
 103095 pts/1    00:00:00 selfdrive.model
 103204 pts/7    00:00:00 ps```

2024-06-09 00:51 UTC, adeebshihadeh commented
Doesn't seem to work with `htop` still.

2024-06-11 01:59 UTC, adeebshihadeh commented
Ended up merging #32667 since it made the agnos-builder PR and had a test.

2024-06-11 01:59 UTC, closed without merging