tici/hardware.py: safe modem access with try-except block
commaai/openpilot pull request #32849
Opened 2024-06-27 14:17 UTC by deanlee

The get_modem() method may fail and raise exceptions. encapsulating it within a try-except block ensures safe access to the modem.

2024-07-13 00:10 UTC, adeebshihadeh requested changes
This is generally a problem with the Hardware classes. We have to come up with a better pattern than the try/excepts everywhere.

2024-07-13 10:21 UTC, deanlee commented
Most functions use decorators to handle exceptions now, except for `get_nvme_temperatures`, `get_modem_data_usage`, and `get_imei`. This is because both `get_nvme_temperatures` and `get_modem_data_usage` will throw exceptions if `wwan0` does not exist or if the command `sudo smartctl -aj /dev/nvme0` fails. If decorators were used to handle these exceptions, each call  would output messages like:
> "Exception in get_modem_data_usage: org.freedesktop.NetworkManager.UnknownDevice: No device found for the requested iface."
> "Exception in get_nvme_temperatures: Command 'sudo smartctl -aj /dev/nvme0' returned non-zero exit status 2."

`get_imei` has its exceptions handled by the caller (registration.py), so it does not need a decorator.:

> 
>       try:
>         imei1, imei2 = HARDWARE.get_imei(0), HARDWARE.get_imei(1)
>       except Exception:
>         cloudlog.exception("Error getting imei, trying again...")
>         time.sleep(1)

2024-08-31 20:57 UTC, adeebshihadeh requested changes

2024-09-04 05:57 UTC, closed without merging

2024-09-04 06:26 UTC, maxime-desroches commented
This PR was closed because of a git history rewrite.
Please read https://github.com/commaai/openpilot/issues/33399 for what to do with your fork and your PRs.