fix bug in modelV2 service which was triggering test_loggerd failure
commaai/openpilot pull request #32892
Opened 2024-07-02 05:17 UTC by Quantizr

**Description**

Decimation of modelV2 was incorrectly set to 0. This caused 
```cpp
const bool in_qlog = service.freq != -1 && (service.counter++ % service.freq == 0);
```
in [system/loggerd/logger.cc](https://github.com/commaai/openpilot/blob/master/system/loggerd/logger.cc) to fail since modulo 0 is undefined. (`.freq = it.decimation` earlier in the file)

The bug would randomly cause any number of the below unit test failures as services are randomly sampled in each test in [test_loggerd.py](https://github.com/commaai/openpilot/blob/master/system/loggerd/tests/test_loggerd.py)
```
FAILED system/loggerd/tests/test_loggerd.py::TestLoggerd::test_rlog - AssertionError: assert False
FAILED system/loggerd/tests/test_loggerd.py::TestLoggerd::test_not_preserving_unflagged_segments - AssertionError: assert False
FAILED system/loggerd/tests/test_loggerd.py::TestLoggerd::test_preserving_flagged_segments - AssertionError: assert False
FAILED system/loggerd/tests/test_loggerd.py::TestLoggerd::test_qlog - AssertionError: assert False
```

**Verification**

Added `["modelV2"]` to the services array which is passed to `self._publish_random_messages(services)` which guaranteed an error every test run. Removing the decimation (making it None) fixed the error and any subsequent division by zero errors caused by dividing by the decimation value.

Interestingly, despite rebuilding with `scons -c` and `scons --no-cache` after making the fix, the problem persisted until I made a clean install of openpilot, leading me on a wild goose chase as it incorrectly appeared the bug was elsewhere.

Perhaps adding all services to the unit tests instead of a random sampling would be better for the future?

2024-07-02 17:53 UTC, adeebshihadeh commented
> Interestingly, despite rebuilding with scons -c and scons --no-cache after making the fix, the problem persisted until I made a clean install of openpilot, leading me on a wild goose chase as it incorrectly appeared the bug was elsewhere

Sounds like we've also got a bug in setting up build dependencies. Can you look into that too?

2024-07-02 17:54 UTC, adeebshihadeh requested changes

2024-07-02 17:54 UTC, adeebshihadeh commented on cereal/services.py
> -  "modelV2": (True, 20., 0),
let's add an assert to prevent this from happening in the future

2024-07-04 00:15 UTC, Quantizr commented
> > Interestingly, despite rebuilding with scons -c and scons --no-cache after making the fix, the problem persisted until I made a clean install of openpilot, leading me on a wild goose chase as it incorrectly appeared the bug was elsewhere
> 
> Sounds like we've also got a bug in setting up build dependencies. Can you look into that too?

Seems like the build dependencies are fine. I looked over the build dependencies and spent a while trying to reproduce what happened the first time, everything works as intended. 
Turns out the first few times I was testing changes, I was running scons from inside openpilot/system/loggerd so changes in services.py were not being built and later while testing other changes I had left the decimation as 0.

2024-07-04 00:22 UTC, merged