Nissan/carcontroller: add_max_steering_angle_nissan
commaai/openpilot pull request #33020
Opened 2024-07-19 16:14 UTC by bongbui321

Resolves: https://github.com/commaai/openpilot/issues/32978

Unlikely this is going to happen in real scenario, but I think it's worth to have a safeguard. It seems that panda decodes by adding a 1310 offset to the angle and this might have something to do with this issue

2024-07-20 00:23 UTC, sshane commented
It could make sense to have a global angle limit for angle control cars that's well below the max of any angle car. Also would be nice if CANPacker gave a warning for out of range values instead of wrapping

2024-07-24 00:17 UTC, adeebshihadeh requested changes
The change itself looks fine, but let's get this fixed up in the CANPacker too:
- [ ] CANPacker prints a warning when this happens
- [ ] CANPacker can optionally assert on that warning, and we'll set that option in CI. similar to `PYTHONWARNINGS=error` or `-Werror`

2024-07-27 19:17 UTC, bongbui321 commented
> It could make sense to have a global angle limit for angle control cars that's well below the max of any car

This sounds nice, though I'm hesitant to put up PRs for this knowing very little on car stuff. maybe just get the max angle from the angle possible from angle-based cars?

2024-08-20 05:36 UTC, sshane commented
We've moved the car interfacing code to our [`opendbc`](https://github.com/commaai/opendbc) repository, which is now the new home for car ports and fingerprints. Please re-open your pull request against [`opendbc`](https://github.com/commaai/opendbc) at your convenience by using this command below. This will transform all changes under `selfdrive/car/` to `opendbc/opendbc/car/`. Make sure you have initialized submodules beforehand and have checked out the latest `opendbc` commit.

```bash
PR_NUMBER=33045
curl -L https://github.com/commaai/openpilot/pull/$PR_NUMBER.patch | sed -e 's/selfdrive\/car/opendbc_repo\/opendbc\/car/g' | git apply -v --reject
```

Simply replace the PR number with your own. Once done, add the files, fix any conflicts, and open a new PR. Alternatively, you may start a new PR from scratch if that is easier for you.

2024-08-20 05:36 UTC, closed without merging