unpin numpy
commaai/openpilot pull request #33132
Opened 2024-07-29 20:21 UTC by maxime-desroches

2024-07-29 20:43 UTC, adeebshihadeh requested changes

2024-07-29 20:43 UTC, adeebshihadeh commented on .github/workflows/selfdrive_tests.yaml
> +    - run: rm -rf /tmp/scons_cache/*
we need to fix this scons dependency properly

2024-07-29 20:58 UTC, adeebshihadeh commented on .github/workflows/selfdrive_tests.yaml
> +    - run: rm -rf /tmp/scons_cache/*
good example of why we need to do this properly, from latest master: https://github.com/commaai/openpilot/actions/runs/10151615366/job/28071268349

2024-07-30 17:50 UTC, adeebshihadeh commented on site_scons/site_tools/cython.py
> +  env.Depends(str(source[0]).split('.')[0] + env["CYTHONCFILESUFFIX"], np.__file__)
you sure you don't want to add this to the scanner?

2024-07-30 19:13 UTC, maxime-desroches commented
Most packages still don't support numpy >= 2.0.0 (rerun for example)

2024-07-30 20:11 UTC, merged