ui: show personality updates
commaai/openpilot pull request #33406
Opened 2024-08-30 02:41 UTC by royjr

untested pr for #33404

2024-08-30 04:58 UTC, adeebshihadeh requested changes

2024-08-30 04:58 UTC, adeebshihadeh commented on selfdrive/controls/lib/events.py
> +    f"{personality}",
should be a one liner

2024-08-30 04:58 UTC, adeebshihadeh commented on selfdrive/controls/lib/events.py
> +    Priority.LOW, VisualAlert.steerRequired, AudibleAlert.promptRepeat, 2.)
no visual or audible alert. also maybe 2s is too long?

2024-08-30 20:58 UTC, sshane commented on selfdrive/controls/lib/events.py
> +  personality = log.LongitudinalPersonality
make global constant

2024-08-30 21:00 UTC, sshane commented on selfdrive/controls/lib/events.py
> +    personality_text = "aggressive"
just do str() on the field

2024-08-31 22:56 UTC, royjr commented
it works but probably need to add `control_state: log.ControlsState` to the rest of the alerts like I did to `startup_master_alert`

2024-08-31 23:00 UTC, adeebshihadeh commented on selfdrive/controls/controlsd.py
> +    self.controlsState = dat.controlsState
don't modify all these lines

2024-08-31 23:00 UTC, adeebshihadeh commented on selfdrive/controls/lib/events.py
> +    personality_text = "Standard"
str(personality).upper()

2024-09-01 03:35 UTC, adeebshihadeh commented
Thanks @royjr.

2024-09-01 03:38 UTC, merged