Improved experience for new developers: documentation & environment setup
commaai/openpilot pull request #34317
Opened 2024-12-27 16:06 UTC by MikeBusuttil

- Links to recently updated [system requirements](https://github.com/commaai/openpilot/wiki/Requirements) and [WSL](https://github.com/commaai/openpilot/wiki/WSL) wiki articles
  - WSL-specific instructions and issues moved to wiki
- Link to thorough [Intro to Openpilot](https://github.com/commaai/openpilot/wiki/Introduction-to-openpilot) wiki
- removed redundant steps from installation documentation

2024-12-27 16:07 UTC, MikeBusuttil commented on tools/install_ubuntu_dependencies.sh
> +    libfreeimage3 \
required for rerun

2024-12-27 16:07 UTC, MikeBusuttil commented on tools/install_ubuntu_dependencies.sh
> +    pocl-opencl-icd \
required for OpenCL

2024-12-27 16:08 UTC, MikeBusuttil commented on tools/install_ubuntu_dependencies.sh
> +    pulseaudio \
required for audio on WSL2

2024-12-27 16:10 UTC, MikeBusuttil commented on tools/README.md
> -
op.sh takes care of Git LFS (which is now installed with git on Ubuntu 24.04)

2025-01-06 02:16 UTC, MikeBusuttil commented
yo @adeebshihadeh or @jyoung8607 are you boys able to give me a quick review on this

2025-01-06 19:08 UTC, jyoung8607 commented on tools/README.md
> -
I'm neutral on moving the WSL stuff to Wiki, but if we're going to move it, we need to preserve the explicit instruction to use Ubuntu 24.04 as the distribution.

2025-01-06 19:20 UTC, jyoung8607 commented on tools/README.md
> -
We should replace 1-3 with `bash <(curl -fsSL openpilot.comma.ai)`.

2025-01-06 19:42 UTC, jyoung8607 requested changes
This should probably be broken into pieces

2025-01-06 19:42 UTC, jyoung8607 commented on tools/install_ubuntu_dependencies.sh
> +    libfreeimage3 \
Let's leave these out for now, I'm not sure rerun is moving forward.

2025-01-06 19:42 UTC, jyoung8607 commented on tools/install_ubuntu_dependencies.sh
> +    pocl-opencl-icd \
Required for webcam only, which is a relatively rare need. I just checked on my machine, it wants to drag in 22 dependencies and 845MB of disk. Let's leave it as manual for webcam users.

2025-01-06 19:42 UTC, jyoung8607 commented on tools/install_ubuntu_dependencies.sh
> +    pulseaudio \
I don't think this is a good idea. Native Ubuntu 24.04 is using pipewire instead of pulseaudio; `apt` wants to remove pipewire when asked to install pulseaudio. This is a big change to user systems that we shouldn't be making. Maybe just add it to the WSL2 wiki.

2025-01-07 05:08 UTC, MikeBusuttil commented on tools/install_ubuntu_dependencies.sh
> +    pocl-opencl-icd \
FYI it's also required for `sim` users.  You're right, It is hefty, as are the CUDA drivers - but these are important to mention to devs that'll be attempting to run anything that uses models.  I'll mention it in the docs instead.

2025-01-07 05:09 UTC, MikeBusuttil commented on tools/install_ubuntu_dependencies.sh
> +    libfreeimage3 \
ok sure.  I'll put them in the WSL docs

2025-01-07 05:17 UTC, MikeBusuttil commented on tools/README.md
> -
Agreed, but I think it's pretty explicit both [here](https://github.com/commaai/openpilot/blob/9816116997dd95cbb488c0af260b4ab6ca951e03/tools/README.md) and on [the WSL wiki](https://github.com/commaai/openpilot/wiki/WSL).  Do you think it needs to be made more explicit?

2025-01-07 05:29 UTC, MikeBusuttil commented on tools/install_ubuntu_dependencies.sh
> +    pulseaudio \
ya that's fair.  I'll try pipewire instead on WSL and make sure that behaves nicely

2025-01-07 20:04 UTC, maxime-desroches commented on tools/install_ubuntu_dependencies.sh
> +    pocl-opencl-icd \
Please be very mindful before adding packages to this list since it makes everything big and slow.

 The `pocl` icd is also very slow since it is a software implementation of `opencl`, so it is better to mention it as a last resort for people without a driver installed already.

2025-01-08 01:06 UTC, MikeBusuttil commented on tools/install_ubuntu_dependencies.sh
> +    pocl-opencl-icd \
That's good to know Max, I wasn't aware,  I'll remove it from here and add it to some documentation elsewhere

2025-01-19 02:01 UTC, closed without merging