Lexus GS300H port
commaai/openpilot pull request #620
Opened 2019-04-26 17:12 UTC by wocsor

also naturally there's a fingerprint included, not sure if that counts toward the fingerprint bounty

a few interesting caveats:

1) there is a DSU which cannot be unplugged. since there's not an accel_command found, we can't get long control yet, even though it uses the Prius radar. the DSU also is the only ECU reporting MAIN_ON and SET_SPEED as far as i can tell.

2) it uses switch config 0111 / 0101

2019-04-27 05:51 UTC, vanillagorillaa commented
Mind getting the DBCs in a PR of their own in the openDBC repo?

2019-04-27 14:30 UTC, wocsor commented
can do, I kind of jumped the gun and submitted to PR before realizing that I needed a different DBC

2019-05-02 00:41 UTC, quillford commented
my techinfo subscription expired, but if I'm remembering right it's DSU wiring/functions are the same as the IS so among the other things you mentioned, you'll lose the cruise stalk after the DSU is unplugged

2019-05-02 17:06 UTC, legonigel requested changes
Can you also remove ubloxd changes from this PR?

2019-05-02 17:06 UTC, legonigel commented on openpilot
> +/data/openpilot
This shouldn't be included in the PR.

2019-05-02 17:06 UTC, legonigel commented on selfdrive/locationd/kalman/loc_local.cpp
> +#define _CFFI_
This file should not be in this PR.

2019-05-02 18:55 UTC, wocsor commented
@legonigel files removed

2019-05-05 08:28 UTC, rbiasini commented
@wocsor , could you please post or PM me a Cabana drive with this car?

2019-05-15 02:54 UTC, wocsor commented
https://community.comma.ai/cabana/?route=19dedb70eae4d01e%7C2019-04-27--13-38-24&max=18&url=https%3A%2F%2Fchffrprivate.blob.core.windows.net%2Fchffrprivate3%2Fv2%2F19dedb70eae4d01e%2F30c2fe159ee89e9457599eeba8e39b1b_2019-04-27--13-38-24

sorry that took a while!

2019-06-15 18:14 UTC, geohot commented
Can you add the car support to the README in the table? (need a template for car ports!)

If so, @rbiasini is there anything else to check? Otherwise it looks good to me. Appreciate you doing these PRs @wocsor

2019-06-26 17:50 UTC, wocsor commented
thanks! readme has been updated. let me know if anything else is needed for this to be upstreamed.

2019-12-02 13:20 UTC, closed without merging