loading progress
commaai/openpilot pull request #792
Opened 2019-08-26 01:40 UTC by dekerr

Here's a working version of #768 
It's not everything I had envisioned, but unfortunately, my ubuntu hard drive died shortly after. 
I still think it's useful in it's current state, so I'm putting up the PR sans progress bar for now.

2019-08-26 14:45 UTC, pd0wm requested changes

2019-08-27 15:03 UTC, pd0wm commented on selfdrive/manager.py
> +    if os.getenv("PREPAREONLY") is None:
You're right!

2019-08-27 15:04 UTC, pd0wm commented on selfdrive/ui/spinner/spinner.c
> -  if (argc >= 2) {
That would be nice. That keeps the spinner versatile and easy to call from a shells script.

2019-08-27 15:05 UTC, pd0wm commented on selfdrive/manager.py
> +  loader_proc = subprocess.Popen(["./spinner"], stdin=subprocess.PIPE,
Didn't mean you should use tqdm, just an example of the API you could use.

2019-09-14 18:19 UTC, ErichMoraga commented
Forget about the spinner.  Text detailing what processes are loading, etc. would be sufficient.

2019-09-17 19:47 UTC, pd0wm commented
The spinner was refactored a little bit, so we can also use it in the NEOS installer. Unfortunately we forgot to open source the files after they were moved. I just pushed those files to devel (#812).

2019-09-18 19:58 UTC, pd0wm commented
I'll finish the PR and merge it internally! I'll probably add a progress bar too.

2019-09-18 19:58 UTC, closed without merging

2019-09-18 20:36 UTC, pd0wm commented
Thanks @dekerr for figuring out the stdin stuff!

![ezgif-2-35311e685540](https://user-images.githubusercontent.com/1314752/65183865-36cdb800-da19-11e9-8288-728f4a05bb03.gif)

2019-09-18 21:56 UTC, dekerr commented
Awesome. Thanks, Willem. Looks great.